/**
 * src/db/seeds/players.ts
 *
 * FIFA World Cup 2026 — Complete squad data for all 48 nations (~1,250 players).
 * Prices are in millions (£m) reflecting each player's fantasy value.
 * Range: GK £4.5–9.5 · DEF £4.5–10.5 · MID £4.5–12.0 · FWD £4.5–13.0
 */

export type RawPlayer = {
  firstName: string;
  lastName: string;
  position: "GK" | "DEF" | "MID" | "FWD";
  nation: string;
  club: string;
  price: number;
};

function p(
  name: string,
  pos: "GK" | "DEF" | "MID" | "FWD",
  nation: string,
  club: string,
  price: number
): RawPlayer {
  const idx = name.indexOf(" ");
  return {
    firstName: idx === -1 ? name : name.slice(0, idx),
    lastName: idx === -1 ? "" : name.slice(idx + 1),
    position: pos,
    nation,
    club,
    price,
  };
}

export const ALL_PLAYERS: RawPlayer[] = [
  // ── GROUP A ────────────────────────────────────────

  // Mexico
  p("Carlos Acevedo", "GK", "Mexico", "Santos Laguna", 4),
  p("Guillermo Ochoa", "GK", "Mexico", "AEL Limassol", 4.2),
  p("Raúl Rangel", "GK", "Mexico", "Chivas", 3.9),
  p("Jesús Gallardo", "DEF", "Mexico", "Toluca", 4.7),
  p("Israel Reyes", "DEF", "Mexico", "América", 4),
  p("César Montes", "DEF", "Mexico", "Lokomotiv Moscow", 4.7),
  p("Jorge Sánchez", "DEF", "Mexico", "PAOK", 4),
  p("Johan Vásquez", "DEF", "Mexico", "Genoa", 4.7),
  p("Mateo Chávez", "DEF", "Mexico", "AZ Alkmaar", 3.5),
  p("Gilberto Mora", "MID", "Mexico", "Tijuana", 4.5),
  p("Edson Álvarez", "MID", "Mexico", "Fenerbahçe", 6),
  p("Orbelín Pineda", "MID", "Mexico", "AEK Athens", 6.2),
  p("Luis Romo", "MID", "Mexico", "Chivas", 5.5),
  p("Brian Gutiérrez", "MID", "Mexico", "Chivas", 5),
  p("Obed Vargas", "MID", "Mexico", "Atlético Madrid", 4.7),
  p("César Huerta", "MID", "Mexico", "Anderlecht", 6.3),
  p("Luis Chávez", "MID", "Mexico", "Dinamo Moscow", 6.3),
  p("Erik Lira", "MID", "Mexico", "Cruz Azul", 5.6),
  p("Álvaro Fidalgo", "MID", "Mexico", "Real Betis", 6.4),
  p("Roberto Alvarado", "MID", "Mexico", "Chivas", 5.3),
  p("Armando González", "FWD", "Mexico", "Chivas", 4.4),
  p("Raúl Jiménez", "FWD", "Mexico", "Fulham", 7),
  p("Julián Quiñones", "FWD", "Mexico", "Al Qadsiah", 5.6),
  p("Santiago Gimenez", "FWD", "Mexico", "AC Milan", 6.8),
  p("Guillermo Martínez", "FWD", "Mexico", "Pumas", 4.7),
  p("Alexis Vega", "FWD", "Mexico", "Toluca", 5.3),

  // South Africa
  p("Ronwen Williams", "GK", "South Africa", "Mamelodi Sundowns", 4.5),
  p("Ricardo Goss", "GK", "South Africa", "Mamelodi Sundowns", 3.7),
  p("Sipho Chaine", "GK", "South Africa", "Orlando Pirates", 3.7),
  p("Khuliso Mudau", "DEF", "South Africa", "Mamelodi Sundowns", 3.6),
  p("Nkosinathi Sibisi", "DEF", "South Africa", "Orlando Pirates", 3.6),
  p("Ime Okon", "DEF", "South Africa", "Hannover 96", 3.5),
  p("Khulumani Ndamane", "DEF", "South Africa", "Mamelodi Sundowns", 3.5),
  p("Aubrey Modiba", "DEF", "South Africa", "Mamelodi Sundowns", 3.7),
  p("Samukelo Kabini", "DEF", "South Africa", "Molde", 4),
  p("Thabang Matuludi", "DEF", "South Africa", "Polokwane City", 3.7),
  p("Olwethu Makhanya", "DEF", "South Africa", "Philadelphia Union", 3.5),
  p("Kamgogelo Sebelebele", "DEF", "South Africa", "Orlando Pirates", 4),
  p("Bradley Cross", "DEF", "South Africa", "Kaizer Chiefs", 3.6),
  p("Mbekezeli Mbokazi", "DEF", "South Africa", "Chicago Fire", 3.5),
  p("Teboho Mokoena", "MID", "South Africa", "Mamelodi Sundowns", 4.3),
  p("Thalente Mbatha", "MID", "South Africa", "Orlando Pirates", 4.9),
  p("Yaya Sithole", "MID", "South Africa", "Tondela", 5.1),
  p("Jayden Adams", "MID", "South Africa", "Mamelodi Sundowns", 4),
  p("Oswin Appollis", "FWD", "South Africa", "Orlando Pirates", 4.9),
  p("Iqraam Rayners", "FWD", "South Africa", "Mamelodi Sundowns", 5.3),
  p("Tshepang Moremi", "FWD", "South Africa", "Orlando Pirates", 4.9),
  p("Relebohile Mofokeng", "FWD", "South Africa", "Orlando Pirates", 4.9),
  p("Evidence Makgopa", "FWD", "South Africa", "Orlando Pirates", 4.5),
  p("Themba Zwane", "FWD", "South Africa", "Mamelodi Sundowns", 4.3),
  p("Lyle Foster", "FWD", "South Africa", "Burnley", 5.4),
  p("Thapelo Maseko", "FWD", "South Africa", "AEL Limassol", 4.2),

  // South Korea
  p("Jo Hyun-Woo", "GK", "South Korea", "Ulsan HD", 4),
  p("Kim Seung-Gyu", "GK", "South Korea", "FC Tokyo", 4.1),
  p("Song Bum-Keun", "GK", "South Korea", "Jeonbuk Hyundai", 3.9),
  p("Kim Min-Jae", "DEF", "South Korea", "Bayern Munich", 5),
  p("Jo Yu-Min", "DEF", "South Korea", "Sharjah", 4),
  p("Lee Han-Beom", "DEF", "South Korea", "Midtjylland", 3.7),
  p("Kim Tae-Hyun", "DEF", "South Korea", "Kashima Antlers", 4),
  p("Park Jin-Seop", "DEF", "South Korea", "Zhejiang FC", 4),
  p("Lee Ki-Hyeok", "DEF", "South Korea", "Gangwon FC", 4),
  p("Lee Tae-Seok", "DEF", "South Korea", "Austria Vienna", 3.7),
  p("Seol Young-Woo", "DEF", "South Korea", "Red Star Belgrade", 4.2),
  p("Jens Castrop", "DEF", "South Korea", "Borussia Mönchengladbach", 5.6),
  p("Kim Moon-Hwan", "DEF", "South Korea", "Daejeon Hana", 3.9),
  p("Yang Hyun-Jun", "MID", "South Korea", "Celtic", 4.7),
  p("Paik Seung-Ho", "MID", "South Korea", "Birmingham City", 5.6),
  p("Hwang In-Beom", "MID", "South Korea", "Feyenoord", 5.8),
  p("Kim Jin-Kyu", "MID", "South Korea", "Jeonbuk Hyundai", 4),
  p("Bae Jun-Ho", "MID", "South Korea", "Stoke City", 5.9),
  p("Um Ji-Sung", "MID", "South Korea", "Swansea City", 4),
  p("Hwang Hee-Chan", "MID", "South Korea", "Wolverhampton", 6.1),
  p("Lee Dong-Gyeong", "MID", "South Korea", "Ulsan HD", 4.9),
  p("Lee Jae-Sung", "MID", "South Korea", "Mainz", 6.2),
  p("Lee Kang-In", "MID", "South Korea", "Paris Saint-Germain", 6.1),
  p("Oh Hyun-Kyu", "FWD", "South Korea", "Besiktas", 5),
  p("Son Heung-Min", "FWD", "South Korea", "LAFC", 7.4),
  p("Cho Kyu-Sung", "FWD", "South Korea", "Midtjylland", 5.5),

  // Czechia
  p("Lukas Hornicek", "GK", "Czechia", "Braga", 3.8),
  p("Jan Koutny", "GK", "Czechia", "Sigma Olomouc", 4),
  p("Jindrich Stanek", "GK", "Czechia", "Slavia Prague", 4),
  p("Vladimír Coufal", "DEF", "Czechia", "TSG Hoffenheim", 3.6),
  p("David Douděra", "DEF", "Czechia", "Slavia Prague", 5.1),
  p("Tomáš Holeš", "DEF", "Czechia", "Slavia Prague", 3.9),
  p("Robin Hranáč", "DEF", "Czechia", "TSG Hoffenheim", 3.9),
  p("Štěpán Chaloupek", "DEF", "Czechia", "Slavia Prague", 3.5),
  p("David Jurásek", "DEF", "Czechia", "Slavia Prague", 3.9),
  p("Ladislav Krejčí", "DEF", "Czechia", "Wolverhampton Wanderers", 4.4),
  p("Jaroslav Zelený", "DEF", "Czechia", "Sparta Prague", 3.9),
  p("David Zima", "DEF", "Czechia", "Slavia Prague", 3.9),
  p("Lukás Cerv", "MID", "Czechia", "Viktoria Plzen", 5.3),
  p("Vladimir Darida", "MID", "Czechia", "Hradec Kralove", 5.3),
  p("Lukás Provod", "MID", "Czechia", "Slavia Prague", 5.9),
  p("Michal Sadílek", "MID", "Czechia", "Slavia Prague", 5.6),
  p("Hugo Sochůrek", "MID", "Czechia", "Sparta Prague", 4.3),
  p("Alexandr Sojka", "MID", "Czechia", "Viktoria Plzen", 4.5),
  p("Tomáš Souček", "MID", "Czechia", "West Ham", 5.6),
  p("Adam Hložek", "FWD", "Czechia", "TSG Hoffenheim", 6.5),
  p("Tomáš Chorý", "FWD", "Czechia", "Slavia Prague", 5.3),
  p("Mojmír Chytil", "FWD", "Czechia", "Slavia Prague", 4.9),
  p("Jan Kuchta", "FWD", "Czechia", "Sparta Prague", 5.5),
  p("Patrik Schick", "FWD", "Czechia", "Bayer Leverkusen", 7.3),
  p("Matej Vydra", "FWD", "Czechia", "Viktoria Plzen", 4),
  p("Denis Višinský", "FWD", "Czechia", "Viktoria Plzen", 4.9),

  // ── GROUP B ────────────────────────────────────────

  // Canada
  p("Dayne St. Clair", "GK", "Canada", "Inter Miami", 3.8),
  p("Maxime Crépeau", "GK", "Canada", "Orlando City", 4),
  p("Owen Goodman", "GK", "Canada", "Barnsley", 3.5),
  p("Moïse Bombito", "DEF", "Canada", "Nice", 4.1),
  p("Derek Cornelius", "DEF", "Canada", "Rangers", 4),
  p("Alphonso Davies", "DEF", "Canada", "Bayern Munich", 4.9),
  p("Luc De Fougerolles", "DEF", "Canada", "FCV Dender", 3.5),
  p("Alistair Johnston", "DEF", "Canada", "Celtic", 4),
  p("Alfie Jones", "DEF", "Canada", "Middlesbrough", 3.8),
  p("Richie Laryea", "DEF", "Canada", "Toronto FC", 3.9),
  p("Niko Sigur", "DEF", "Canada", "Hajduk Split", 4.9),
  p("Joel Waterman", "DEF", "Canada", "Chicago Fire", 3.7),
  p("Ali Ahmed", "MID", "Canada", "Norwich City", 4.9),
  p("Tajon Buchanan", "MID", "Canada", "Villarreal", 5.5),
  p("Mathieu Choinière", "MID", "Canada", "LAFC", 5.3),
  p("Stephen Eustáquio", "MID", "Canada", "LAFC", 5),
  p("Marcelo Flores", "MID", "Canada", "Tigres UANL", 5.7),
  p("Ismaël Koné", "MID", "Canada", "Sassuolo", 6),
  p("Liam Millar", "MID", "Canada", "Hull City", 5.1),
  p("Jonathan Osorio", "MID", "Canada", "Toronto FC", 5.6),
  p("Nathan Saliba", "MID", "Canada", "Anderlecht", 5.1),
  p("Jacob Shaffelburg", "MID", "Canada", "LAFC", 5.2),
  p("Jonathan David", "FWD", "Canada", "Juventus", 7),
  p("Promise David", "FWD", "Canada", "Royale-Union Saint Gilloise", 5.4),
  p("Cyle Larin", "FWD", "Canada", "Southampton", 6.2),
  p("Tani Oluwaseyi", "FWD", "Canada", "Villarreal", 4.9),

  // Bosnia-Herzegovina
  p("Nikola Vasilj", "GK", "Bosnia-Herzegovina", "St Pauli", 4),
  p("Martin Zlomislic", "GK", "Bosnia-Herzegovina", "Rijeka", 3.5),
  p("Osman Hadzikic", "GK", "Bosnia-Herzegovina", "Slaven Belupo", 3.6),
  p("Sead Kolasinac", "DEF", "Bosnia-Herzegovina", "Atalanta", 4.3),
  p("Amar Dedic", "DEF", "Bosnia-Herzegovina", "Benfica", 4.3),
  p("Nihad Mujakic", "DEF", "Bosnia-Herzegovina", "Gaziantep", 3.6),
  p("Nikola Katic", "DEF", "Bosnia-Herzegovina", "Schalke 04", 3.8),
  p("Tarik Muharemovic", "DEF", "Bosnia-Herzegovina", "Sassuolo", 3.9),
  p("Stjepan Radeljic", "DEF", "Bosnia-Herzegovina", "Rijeka", 3.7),
  p("Dennis Hadzikadunic", "DEF", "Bosnia-Herzegovina", "Sampdoria", 3.7),
  p("Nidal Celik", "DEF", "Bosnia-Herzegovina", "Lens", 3.5),
  p("Amir Hadziahmetovic", "MID", "Bosnia-Herzegovina", "Hull City", 5.5),
  p("Ivan Sunjic", "MID", "Bosnia-Herzegovina", "Pafos", 5.1),
  p("Ivan Basic", "MID", "Bosnia-Herzegovina", "Astana", 5.1),
  p("Dzenis Burnic", "MID", "Bosnia-Herzegovina", "Karlsruher SC", 4.9),
  p("Ermin Mahmic", "MID", "Bosnia-Herzegovina", "Slovan Liberec", 4.2),
  p("Benjamin Tahirovic", "MID", "Bosnia-Herzegovina", "Brondby", 5.3),
  p("Amar Memic", "MID", "Bosnia-Herzegovina", "Viktoria Plzen", 4.7),
  p("Armin Gigovic", "MID", "Bosnia-Herzegovina", "Young Boys", 5.1),
  p("Kerim Alajbegovic", "MID", "Bosnia-Herzegovina", "RB Salzburg", 4.2),
  p("Esmir Bajraktarevic", "MID", "Bosnia-Herzegovina", "PSV Eindhoven", 4.7),
  p("Ermedin Demirovic", "FWD", "Bosnia-Herzegovina", "VfB Stuttgart", 6.2),
  p("Jovo Lukic", "FWD", "Bosnia-Herzegovina", "Universitatea Cluj", 5.6),
  p("Samed Bazdar", "FWD", "Bosnia-Herzegovina", "Jagiellonia Bialystok", 4.5),
  p("Haris Tabakovic", "FWD", "Bosnia-Herzegovina", "Borussia Moenchengladbach", 5.1),
  p("Edin Dzeko", "FWD", "Bosnia-Herzegovina", "Schalke 04", 6.1),

  // Qatar
  p("Salah Zakaria", "GK", "Qatar", "Al Duhail", 3.7),
  p("Meshaal Barsham", "GK", "Qatar", "Al Sadd", 4.1),
  p("Mahmoud Abunada", "GK", "Qatar", "Al Rayyan", 4),
  p("Boualem Khoukhi", "DEF", "Qatar", "Al Sadd", 3.8),
  p("Pedro Miguel", "DEF", "Qatar", "Al Sadd", 3.9),
  p("Sultan Al Brake", "DEF", "Qatar", "Al Duhail", 3.7),
  p("Al-Hashmi Al-Hussain", "DEF", "Qatar", "Al Arabi", 3.5),
  p("Ayoub Al-Alawi", "DEF", "Qatar", "Al Gharafa", 4),
  p("Issa Laye", "DEF", "Qatar", "Al Arabi", 3.5),
  p("Lucas Mendes", "DEF", "Qatar", "Al Wakrah", 3.8),
  p("Homam Al-Amin", "DEF", "Qatar", "Cultural Leonesa", 4),
  p("Ahmed Fathi", "MID", "Qatar", "Al Arabi", 4),
  p("Jassim Gaber", "MID", "Qatar", "Al Rayyan", 4),
  p("Assim Madibo", "MID", "Qatar", "Al Wakrah", 5.1),
  p("Abdulaziz Hatem", "MID", "Qatar", "Al Rayyan", 5.3),
  p("Karim Boudiaf", "MID", "Qatar", "Al Duhail", 4.9),
  p("Mohammed Mannai", "MID", "Qatar", "Al Shamal", 4),
  p("Almoez Ali", "FWD", "Qatar", "Al Duhail", 5.3),
  p("Akram Afif", "FWD", "Qatar", "Al Sadd", 5.9),
  p("Tahsin Mohammed", "FWD", "Qatar", "Al Duhail", 4.5),
  p("Edmílson Junior", "FWD", "Qatar", "Al Duhail", 4.9),
  p("Ahmed Al-Ganehi", "FWD", "Qatar", "Al Gharafa", 4.2),
  p("Ahmed Alaa", "FWD", "Qatar", "Al Rayyan", 5.5),
  p("Hassan Al-Haydos", "FWD", "Qatar", "Al Sadd", 4.6),
  p("Mohammed Muntari", "FWD", "Qatar", "Al Gharafa", 5.3),
  p("Yusuf Abdurisag", "FWD", "Qatar", "Al Wakrah", 4.4),

  // Switzerland
  p("Gregor Kobel", "GK", "Switzerland", "Borussia Dortmund", 4.7),
  p("Yvon Mvogo", "GK", "Switzerland", "Lorient", 4.2),
  p("Marvin Keller", "GK", "Switzerland", "Young Boys", 3.7),
  p("Manuel Akanji", "DEF", "Switzerland", "Inter Milan", 5),
  p("Nico Elvedi", "DEF", "Switzerland", "Borussia Mönchengladbach", 4.3),
  p("Ricardo Rodriguez", "DEF", "Switzerland", "Real Betis", 4.5),
  p("Silvan Widmer", "DEF", "Switzerland", "Mainz", 4.2),
  p("Miro Muheim", "DEF", "Switzerland", "Hamburger SV", 4),
  p("Aurèle Amenda", "DEF", "Switzerland", "Eintracht Frankfurt", 3.7),
  p("Eray Cömert", "DEF", "Switzerland", "Valencia", 3.9),
  p("Luca Jaquez", "DEF", "Switzerland", "Stuttgart", 3.5),
  p("Granit Xhaka", "MID", "Switzerland", "Sunderland", 6.2),
  p("Johan Manzambi", "MID", "Switzerland", "Freiburg", 5.6),
  p("Remo Freuler", "MID", "Switzerland", "Bologna", 5.9),
  p("Denis Zakaria", "MID", "Switzerland", "Monaco", 6.1),
  p("Ardon Jashari", "MID", "Switzerland", "AC Milan", 5.2),
  p("Djibril Sow", "MID", "Switzerland", "Sevilla", 6.1),
  p("Christian Fassnacht", "MID", "Switzerland", "Young Boys", 6.1),
  p("Michel Aebischer", "MID", "Switzerland", "Pisa", 5.9),
  p("Fabian Rieder", "MID", "Switzerland", "Augsburg", 6.2),
  p("Rubén Vargas", "MID", "Switzerland", "Sevilla", 6.8),
  p("Breel Embolo", "FWD", "Switzerland", "Rennes", 7.5),
  p("Noah Okafor", "FWD", "Switzerland", "Leeds", 5.9),
  p("Dan Ndoye", "FWD", "Switzerland", "Nottingham Forest", 6.8),
  p("Zeki Amdouni", "FWD", "Switzerland", "Burnley", 4.9),
  p("Cedric Itten", "FWD", "Switzerland", "Fortuna Dusseldorf", 5.4),

  // ── GROUP C ────────────────────────────────────────

  // Brazil
  p("Alisson", "GK", "Brazil", "Liverpool", 5),
  p("Éderson", "GK", "Brazil", "Fenerbahce", 6.3),
  p("Weverton", "GK", "Brazil", "Grêmio", 4.5),
  p("Alex Sandro", "DEF", "Brazil", "Flamengo", 4.5),
  p("Bremer", "DEF", "Brazil", "Juventus", 4.3),
  p("Danilo", "DEF", "Brazil", "Flamengo", 5.6),
  p("Douglas Santos", "DEF", "Brazil", "Zenit St. Petersburg", 4.3),
  p("Gabriel Magalhães", "DEF", "Brazil", "Arsenal", 5.5),
  p("Léo Pereira", "DEF", "Brazil", "Flamengo", 4.2),
  p("Marquinhos", "DEF", "Brazil", "Paris Saint-Germain", 5.2),
  p("Roger Ibañez", "DEF", "Brazil", "Al Ahli", 4.4),
  p("Wesley", "DEF", "Brazil", "AS Roma", 4.5),
  p("Bruno Guimarães", "MID", "Brazil", "Newcastle United", 6.8),
  p("Casemiro", "MID", "Brazil", "Manchester United", 6.3),
  p("Danilo Santos", "MID", "Brazil", "Botafogo", 5.6),
  p("Fabinho", "MID", "Brazil", "Al Ittihad", 5.2),
  p("Lucas Paquetá", "MID", "Brazil", "Flamengo", 6.5),
  p("Endrick", "FWD", "Brazil", "Lyon", 5.5),
  p("Gabriel Martinelli", "FWD", "Brazil", "Arsenal", 6.5),
  p("Igor Thiago", "FWD", "Brazil", "Brentford", 5.9),
  p("Luiz Henrique", "FWD", "Brazil", "Zenit St. Petersburg", 6.1),
  p("Matheus Cunha", "FWD", "Brazil", "Manchester United", 7.3),
  p("Neymar", "FWD", "Brazil", "Santos", 7.2),
  p("Raphinha", "FWD", "Brazil", "Barcelona", 8.2),
  p("Rayan", "FWD", "Brazil", "Bournemouth", 5.6),
  p("Vinícius Júnior", "FWD", "Brazil", "Real Madrid", 10),

  // Morocco
  p("Yassine Bounou", "GK", "Morocco", "Al Hilal", 4.7),
  p("Munir El Kajoui", "GK", "Morocco", "RS Berkane", 4),
  p("Reda Tagnaouti", "GK", "Morocco", "AS Far", 4),
  p("Noussair Mazraoui", "DEF", "Morocco", "Manchester United", 4.4),
  p("Anass Salah-Eddine", "DEF", "Morocco", "PSV Eindhoven", 3.9),
  p("Youssef Belammari", "DEF", "Morocco", "Al Ahly", 3.6),
  p("Achraf Hakimi", "DEF", "Morocco", "Paris Saint-Germain", 6),
  p("Zakaria El Ouahdi", "DEF", "Morocco", "Racing Genk", 4.1),
  p("Chadi Riad", "DEF", "Morocco", "Crystal Palace", 3.9),
  p("Nayef Aguerd", "DEF", "Morocco", "Marseille", 4.3),
  p("Redouane Halhal", "DEF", "Morocco", "KV Mechelen", 3.5),
  p("Issa Diop", "DEF", "Morocco", "Fulham", 4.5),
  p("Samir El Mourabet", "MID", "Morocco", "Strasbourg", 4.7),
  p("Ayyoub Bouaddi", "MID", "Morocco", "Lille", 5.5),
  p("Neil El Aynaoui", "MID", "Morocco", "AS Roma", 5.6),
  p("Sofyan Amrabat", "MID", "Morocco", "Real Betis", 5.9),
  p("Azzedine Ounahi", "MID", "Morocco", "Girona", 6.2),
  p("Bilal El Khannouss", "MID", "Morocco", "Stuttgart", 6.2),
  p("Ismael Saibari", "MID", "Morocco", "PSV Eindhoven", 6.8),
  p("Abde Ezzalzouli", "FWD", "Morocco", "Real Betis", 5.3),
  p("Chemsdine Talbi", "FWD", "Morocco", "Sunderland", 4.4),
  p("Soufiane Rahimi", "FWD", "Morocco", "Al Ain", 5.6),
  p("Ayoub El Kaabi", "FWD", "Morocco", "Olympiacos", 5.9),
  p("Brahim Díaz", "FWD", "Morocco", "Real Madrid", 6.4),
  p("Gessime Yassine", "FWD", "Morocco", "Strasbourg", 4),
  p("Ayoube Amaimouni", "FWD", "Morocco", "Eintracht Frankfurt", 4.3),

  // Haiti
  p("Johny Placide", "GK", "Haiti", "Bastia", 3.9),
  p("Alexandre Pierre", "GK", "Haiti", "Sochaux", 3.6),
  p("Josue Duverger", "GK", "Haiti", "Cosmos Koblenz", 3.5),
  p("Carlens Arcus", "DEF", "Haiti", "Angers", 3.8),
  p("Wilguens Paugain", "DEF", "Haiti", "Zulte Waregem", 3.5),
  p("Duke Lacroix", "DEF", "Haiti", "Colorado Springs Switchbacks", 3.5),
  p("Martin Expérience", "DEF", "Haiti", "Nancy", 3.5),
  p("Jean-Kévin Duverne", "DEF", "Haiti", "Gent", 3.8),
  p("Ricardo Adé", "DEF", "Haiti", "LDU Quito", 3.5),
  p("Hannes Delcroix", "DEF", "Haiti", "Lugano", 3.7),
  p("Keeto Thermoncy", "DEF", "Haiti", "Young Boys", 3.5),
  p("Carl Fred Sainté", "MID", "Haiti", "El Paso Locomotive", 4),
  p("Leverton Pierre", "MID", "Haiti", "Vizela", 4.2),
  p("Danley Jean Jacques", "MID", "Haiti", "Philadelphia Union", 4.7),
  p("Jean-Ricner Bellegarde", "MID", "Haiti", "Wolverhampton Wanderers", 4.7),
  p("Woodensky Pierre", "MID", "Haiti", "Violette", 4.2),
  p("Dominique Simon", "MID", "Haiti", "FC Tatran Prešov", 4.3),
  p("Don Deedson Louicius", "FWD", "Haiti", "FC Dallas", 4),
  p("Josué Casimir", "FWD", "Haiti", "Auxerre", 4.2),
  p("Derrick Etienne", "FWD", "Haiti", "Toronto FC", 4.4),
  p("Ruben Providence", "FWD", "Haiti", "Almere", 4),
  p("Duckens Nazon", "FWD", "Haiti", "Esteghlal", 6),
  p("Frantzdy Pierrot", "FWD", "Haiti", "Çaykur Rizespor", 4.7),
  p("Wilson Isidor", "FWD", "Haiti", "Sunderland", 5),
  p("Yassin Fortuné", "FWD", "Haiti", "Vizela", 4.2),
  p("Lenny Joseph", "FWD", "Haiti", "Ferencváros", 4.2),

  // Scotland
  p("Craig Gordon", "GK", "Scotland", "Hearts", 3.5),
  p("Angus Gunn", "GK", "Scotland", "Nottingham Forest", 3.6),
  p("Liam Kelly", "GK", "Scotland", "Rangers", 3.7),
  p("Grant Hanley", "DEF", "Scotland", "Hibernian", 3.5),
  p("Jack Hendry", "DEF", "Scotland", "Al Etiffaq", 3.9),
  p("Aaron Hickey", "DEF", "Scotland", "Brentford", 4.3),
  p("Dom Hyam", "DEF", "Scotland", "Wrexham", 4),
  p("Scott McKenna", "DEF", "Scotland", "Dinamo Zagreb", 3.8),
  p("Nathan Patterson", "DEF", "Scotland", "Everton", 4),
  p("Anthony Ralston", "DEF", "Scotland", "Celtic", 3.8),
  p("Andy Robertson", "DEF", "Scotland", "Liverpool", 5),
  p("John Souttar", "DEF", "Scotland", "Rangers", 3.8),
  p("Kieran Tierney", "DEF", "Scotland", "Celtic", 4.3),
  p("Ryan Christie", "MID", "Scotland", "Bournemouth", 5.6),
  p("Finlay Curtis", "MID", "Scotland", "Kilmarnock", 4),
  p("Lewis Ferguson", "MID", "Scotland", "Bologna", 4.8),
  p("Ben Gannon-Doak", "MID", "Scotland", "Bournemouth", 4.9),
  p("Billy Gilmour", "MID", "Scotland", "Napoli", 5.1),
  p("John McGinn", "MID", "Scotland", "Aston Villa", 6),
  p("Kenny McLean", "MID", "Scotland", "Norwich", 4.8),
  p("Scott McTominay", "MID", "Scotland", "Napoli", 6.5),
  p("Ché Adams", "FWD", "Scotland", "Torino", 5.4),
  p("Lyndon Dykes", "FWD", "Scotland", "Charlton Athletic", 4.6),
  p("George Hirst", "FWD", "Scotland", "Ipswich", 4.6),
  p("Lawrence Shankland", "FWD", "Scotland", "Hearts", 5.5),
  p("Ross Stewart", "FWD", "Scotland", "Southampton", 5.4),

  // ── GROUP D ────────────────────────────────────────

  // United States
  p("Chris Brady", "GK", "United States", "Chicago Fire", 3.5),
  p("Matt Freese", "GK", "United States", "New York City FC", 4.2),
  p("Matt Turner", "GK", "United States", "New England Revolution", 4),
  p("Max Arfsten", "DEF", "United States", "Columbus Crew", 4.4),
  p("Sergiño Dest", "DEF", "United States", "PSV Eindhoven", 4.3),
  p("Alex Freeman", "DEF", "United States", "Villarreal", 4),
  p("Mark McKenzie", "DEF", "United States", "Toulouse", 3.9),
  p("Tim Ream", "DEF", "United States", "Charlotte FC", 3.9),
  p("Chris Richards", "DEF", "United States", "Crystal Palace", 4.1),
  p("Antonee Robinson", "DEF", "United States", "Fulham", 5),
  p("Miles Robinson", "DEF", "United States", "FC Cincinnati", 4),
  p("Joe Scally", "DEF", "United States", "Borussia Mönchengladbach", 4.1),
  p("Auston Trusty", "DEF", "United States", "Celtic", 3.9),
  p("Tyler Adams", "MID", "United States", "AFC Bournemouth", 5.3),
  p("Sebastian Berhalter", "MID", "United States", "Vancouver Whitecaps", 4.7),
  p("Weston McKennie", "MID", "United States", "Juventus", 6.1),
  p("Cristian Roldan", "MID", "United States", "Seattle Sounders", 4.7),
  p("Brenden Aaronson", "MID", "United States", "Leeds United", 5.7),
  p("Malik Tillman", "MID", "United States", "Bayer Leverkusen", 6.1),
  p("Tim Weah", "MID", "United States", "Marseille", 5.5),
  p("Alejandro Zendejas", "MID", "United States", "Club América", 4.5),
  p("Christian Pulisic", "FWD", "United States", "AC Milan", 7),
  p("Gio Reyna", "FWD", "United States", "Borussia Mönchengladbach", 6.5),
  p("Folarin Balogun", "FWD", "United States", "AS Monaco", 6),
  p("Ricardo Pepi", "FWD", "United States", "PSV Eindhoven", 5.9),
  p("Haji Wright", "FWD", "United States", "Coventry City", 5.3),

  // Australia
  p("Mathew Ryan", "GK", "Australia", "Levante", 4.1),
  p("Paul Izzo", "GK", "Australia", "Randers FC", 3.6),
  p("Patrick Beach", "GK", "Australia", "Melbourne City", 3.5),
  p("Jordan Bos", "DEF", "Australia", "Feyenoord Rotterdam", 4),
  p("Aziz Behich", "DEF", "Australia", "Melbourne City", 3.8),
  p("Harry Souttar", "DEF", "Australia", "Leicester City", 4.1),
  p("Alessandro Circati", "DEF", "Australia", "Parma", 3.9),
  p("Lucas Herrington", "DEF", "Australia", "Colorado Rapids", 3.5),
  p("Cameron Burgess", "DEF", "Australia", "Swansea City", 3.8),
  p("Kai Trewin", "DEF", "Australia", "New York City FC", 3.5),
  p("Milos Degenek", "DEF", "Australia", "Apoel Nicosia", 3.8),
  p("Jason Geria", "DEF", "Australia", "Albirex Niigata", 3.7),
  p("Jacob Italiano", "DEF", "Australia", "Grazer AK", 4.2),
  p("Jackson Irvine", "MID", "Australia", "St. Pauli", 5.6),
  p("Aiden O'Neill", "MID", "Australia", "New York City FC", 5.4),
  p("Paul Okon Jr", "MID", "Australia", "Sydney FC", 4.7),
  p("Cameron Devlin", "MID", "Australia", "Heart of Midlothian", 4.7),
  p("Connor Metcalfe", "FWD", "Australia", "St. Pauli", 5.3),
  p("Mathew Leckie", "FWD", "Australia", "Melbourne City", 4.7),
  p("Nishan Velupillay", "FWD", "Australia", "Melbourne Victory", 4.4),
  p("Cristian Volpato", "FWD", "Australia", "Sassuolo", 6),
  p("Nestory Irankunda", "FWD", "Australia", "Watford", 5.1),
  p("Awer Mabil", "FWD", "Australia", "Castellón", 5.6),
  p("Ajdin Hrustic", "FWD", "Australia", "Heracles Almelo", 5.7),
  p("Mohamed Toure", "FWD", "Australia", "Norwich City", 5),
  p("Tete Yengi", "FWD", "Australia", "Machida Zelvia", 4.3),

  // Paraguay
  p("Roberto Fernández", "GK", "Paraguay", "Cerro Porteño", 4),
  p("Orlando Gill", "GK", "Paraguay", "San Lorenzo", 3.5),
  p("Gastón Olveira", "GK", "Paraguay", "Olimpia", 3.8),
  p("Gustavo Gómez", "DEF", "Paraguay", "Palmeiras", 4.6),
  p("Júnior Alonso", "DEF", "Paraguay", "Atletico Mineiro", 4.1),
  p("Fabián Balbuena", "DEF", "Paraguay", "Gremio", 4),
  p("Omar Alderete", "DEF", "Paraguay", "Sunderland", 4.1),
  p("Juan Caceres", "DEF", "Paraguay", "Dynamo Moscow", 4),
  p("Jose Canale", "DEF", "Paraguay", "Lanus", 3.6),
  p("Alexandro Maidana", "DEF", "Paraguay", "Talleres", 4),
  p("Gustavo Velázquez", "DEF", "Paraguay", "Cerro Porteño", 3.8),
  p("Miguel Almirón", "MID", "Paraguay", "Atlanta United", 6),
  p("Kaku", "MID", "Paraguay", "Al Ain", 7.4),
  p("Andrés Cubas", "MID", "Paraguay", "Vancouver Whitecaps", 4.7),
  p("Ramón Sosa", "MID", "Paraguay", "Palmeiras", 5.3),
  p("Diego Gómez", "MID", "Paraguay", "Brighton & Hove Albion", 6.8),
  p("Damián Bobadilla", "MID", "Paraguay", "São Paulo", 5.5),
  p("Braian Ojeda", "MID", "Paraguay", "Orlando City", 5.6),
  p("Matías Galarza", "MID", "Paraguay", "Atlanta United", 4.8),
  p("Maurício", "MID", "Paraguay", "Palmeiras", 4.6),
  p("Antonio Sanabria", "FWD", "Paraguay", "Cremonese", 6.5),
  p("Julio Enciso", "FWD", "Paraguay", "Strasbourg", 6.6),
  p("Gabriel Ávalos", "FWD", "Paraguay", "Independiente", 4.9),
  p("Alex Arce", "FWD", "Paraguay", "Independiente Rivadavia", 4.9),
  p("Isidro Pitta", "FWD", "Paraguay", "Red Bull Bragantino", 5.9),
  p("Gustavo Caballero", "FWD", "Paraguay", "Portsmouth", 4.2),

  // Türkiye
  p("Ugurcan Cakir", "GK", "Türkiye", "Galatasaray", 4.2),
  p("Mert Gunok", "GK", "Türkiye", "Fenerbahce", 4),
  p("Altay Bayindir", "GK", "Türkiye", "Man United", 4),
  p("Merih Demiral", "DEF", "Türkiye", "Al-Ahli", 4),
  p("Zeki Celik", "DEF", "Türkiye", "AS Roma", 4.3),
  p("Caglar Soyuncu", "DEF", "Türkiye", "Fenerbahce", 4.4),
  p("Mert Muldur", "DEF", "Türkiye", "Fenerbahce", 4.1),
  p("Ferdi Kadioglu", "DEF", "Türkiye", "Brighton & Hove Albion", 4.3),
  p("Ozan Kabak", "DEF", "Türkiye", "TSG Hoffenheim", 4),
  p("Abdulkerim Bardakci", "DEF", "Türkiye", "Galatasaray", 4),
  p("Eren Elmali", "DEF", "Türkiye", "Galatasaray", 4),
  p("Samet Akaydin", "DEF", "Türkiye", "Caykur Rizesport", 4.1),
  p("Hakan Calhanoglou", "MID", "Türkiye", "Inter Milan", 8),
  p("Kaan Ayhan", "MID", "Türkiye", "Galatasaray", 4.5),
  p("Orkun Kokcu", "MID", "Türkiye", "Besiktas", 6),
  p("Ismail Yuksek", "MID", "Türkiye", "Fenerbahce", 4.6),
  p("Salih Ozcan", "MID", "Türkiye", "Borussia Dortmund", 4.7),
  p("Kerem Akturkoglu", "FWD", "Türkiye", "Fenerbahce", 6.2),
  p("Irfan Can Kahveci", "FWD", "Türkiye", "Kasimpasa", 5.9),
  p("Baris Apler Yilmaz", "FWD", "Türkiye", "Galatasaray", 5.5),
  p("Arda Guler", "FWD", "Türkiye", "Real Madrid", 7),
  p("Kenan Yildiz", "FWD", "Türkiye", "Juventus", 7),
  p("Yunus Akgun", "FWD", "Türkiye", "Galatasaray", 4.9),
  p("Oguz Aydin", "FWD", "Türkiye", "Fenerbahce", 5),
  p("Deniz Gul", "FWD", "Türkiye", "Porto", 4.4),
  p("Can Uzun", "FWD", "Türkiye", "Eintracht Frankfurt", 5.3),

  // ── GROUP E ────────────────────────────────────────

  // Germany
  p("Oliver Baumann", "GK", "Germany", "Hoffenheim", 4.3),
  p("Manuel Neuer", "GK", "Germany", "Bayern Munich", 5),
  p("Alexander Nübel", "GK", "Germany", "Stuttgart", 4.7),
  p("Waldemar Anton", "DEF", "Germany", "Borussia Dortmund", 3.9),
  p("Nathaniel Brown", "DEF", "Germany", "Eintracht Frankfurt", 4.7),
  p("David Raum", "DEF", "Germany", "RB Leipzig", 4.9),
  p("Antonio Rüdiger", "DEF", "Germany", "Real Madrid", 5.5),
  p("Nico Schlotterbeck", "DEF", "Germany", "Borussia Dortmund", 5.3),
  p("Jonathan Tah", "DEF", "Germany", "Bayern Munich", 5.3),
  p("Malick Thiaw", "DEF", "Germany", "Newcastle", 4.7),
  p("Pascal Gross", "MID", "Germany", "Brighton", 5.6),
  p("Joshua Kimmich", "MID", "Germany", "Bayern Munich", 5.5),
  p("Felix Nmecha", "MID", "Germany", "Borussia Dortmund", 5.6),
  p("Aleksandar Pavlovic", "MID", "Germany", "Bayern Munich", 5.5),
  p("Angelo Stiller", "MID", "Germany", "Stuttgart", 5.8),
  p("Leon Goretzka", "MID", "Germany", "Bayern Munich", 6.1),
  p("Florian Wirtz", "MID", "Germany", "Liverpool", 7.5),
  p("Jamie Leweling", "MID", "Germany", "Stuttgart", 6.4),
  p("Maximilian Beier", "FWD", "Germany", "Borussia Dortmund", 6.5),
  p("Kai Havertz", "FWD", "Germany", "Arsenal", 7.8),
  p("Lennart Karl", "FWD", "Germany", "Bayern Munich", 4.8),
  p("Jamal Musiala", "FWD", "Germany", "Bayern Munich", 8),
  p("Leroy Sané", "FWD", "Germany", "Galatasaray", 7.4),
  p("Deniz Undav", "FWD", "Germany", "Stuttgart", 6.6),
  p("Nick Woltemade", "FWD", "Germany", "Newcastle", 7.2),

  // Curacao
  p("Eloy Room", "GK", "Curacao", "Miami FC", 3.9),
  p("Tyrick Bodak", "GK", "Curacao", "Telstar", 3.5),
  p("Trevor Doornbusch", "GK", "Curacao", "VVV Venlo", 3.6),
  p("Riechedly Bazoer", "DEF", "Curacao", "Konyaspor", 3.8),
  p("Joshua Brenet", "DEF", "Curacao", "Kayserispor", 3.7),
  p("Roshon van Eijma", "DEF", "Curacao", "RKC Waalwijk", 3.5),
  p("Sherel Floranus", "DEF", "Curacao", "PEC Zwolle", 3.6),
  p("Deveron Fonville", "DEF", "Curacao", "NEC Nijmegen", 3.7),
  p("Jurien Gaari", "DEF", "Curacao", "Abha", 3.5),
  p("Armando Obispo", "DEF", "Curacao", "PSV Eindhoven", 3.7),
  p("Shurandy Sambo", "DEF", "Curacao", "Sparta Rotterdam", 3.6),
  p("Juninho Bacuna", "MID", "Curacao", "Volendam", 5.1),
  p("Leandro Bacuna", "MID", "Curacao", "Igdir", 4),
  p("Livano Comenencia", "MID", "Curacao", "Zurich", 4.5),
  p("Kevin Felida", "MID", "Curacao", "Den Bosch", 4.5),
  p("Ar'jany Martha", "MID", "Curacao", "Rotherham United", 3.5),
  p("Tyrese Noslin", "MID", "Curacao", "Telstar", 3.5),
  p("Godfried Roemeratoe", "MID", "Curacao", "RKC Waalwijk", 4.7),
  p("Jeremy Antonisse", "FWD", "Curacao", "Kifisia", 4),
  p("Tahith Chong", "FWD", "Curacao", "Sheffield United", 4.2),
  p("Kenji Gorre", "FWD", "Curacao", "Maccabi Haifa", 4.2),
  p("Sontje Hansen", "FWD", "Curacao", "Middlesbrough", 4.4),
  p("Gervane Kastaneer", "FWD", "Curacao", "Terengganu", 4),
  p("Brandley Kuwas", "FWD", "Curacao", "Volendam", 4.4),
  p("Jurgen Locadia", "FWD", "Curacao", "Miami FC", 4.1),
  p("Jearl Margaritha", "FWD", "Curacao", "Beveren", 4.2),

  // Côte d'Ivoire
  p("Yahia Fofana", "GK", "Côte d'Ivoire", "Rizespor", 4.2),
  p("Mohamed Koné", "GK", "Côte d'Ivoire", "Charleroi", 3.7),
  p("Alban Lafont", "GK", "Côte d'Ivoire", "Panathinaikos", 4.1),
  p("Emmanuel Agbadou", "DEF", "Côte d'Ivoire", "Beşiktaş", 3.9),
  p("Clément Akpa", "DEF", "Côte d'Ivoire", "AJ Auxerre", 3.6),
  p("Ousmane Diomande", "DEF", "Côte d'Ivoire", "Sporting CP", 4.3),
  p("Guela Doué", "DEF", "Côte d'Ivoire", "Strasbourg", 3.9),
  p("Ghislain Konan", "DEF", "Côte d'Ivoire", "Gil Vicente", 4),
  p("Odilon Kossounou", "DEF", "Côte d'Ivoire", "Atalanta", 4.3),
  p("Evan Ndicka", "DEF", "Côte d'Ivoire", "AS Roma", 4.4),
  p("Wilfried Singo", "DEF", "Côte d'Ivoire", "Galatasaray", 4.4),
  p("Seko Fofana", "MID", "Côte d'Ivoire", "Porto", 6.8),
  p("Parfait Guiagon", "MID", "Côte d'Ivoire", "Charleroi", 4.9),
  p("Franck Kessié", "MID", "Côte d'Ivoire", "Al Ahli", 5.9),
  p("Christ Inao Oulaï", "MID", "Côte d'Ivoire", "Trabzonspor", 4.6),
  p("Ibrahim Sangaré", "MID", "Côte d'Ivoire", "Nottingham Forest", 5.8),
  p("Jean Michaël Seri", "MID", "Côte d'Ivoire", "NK Maribor", 5.5),
  p("Simon Adingra", "FWD", "Côte d'Ivoire", "AS Monaco", 5.6),
  p("Ange-Yoan Bonny", "FWD", "Côte d'Ivoire", "Internazionale", 4.9),
  p("Amad Diallo", "FWD", "Côte d'Ivoire", "Manchester United", 5.9),
  p("Oumar Diakité", "FWD", "Côte d'Ivoire", "Cercle Brugge", 5.3),
  p("Yan Diomande", "FWD", "Côte d'Ivoire", "RB Leipzig", 5.9),
  p("Evann Guessand", "FWD", "Côte d'Ivoire", "Aston Villa", 5.3),
  p("Nicolas Pépé", "FWD", "Côte d'Ivoire", "Villarreal", 5.9),
  p("Bazoumana Touré", "FWD", "Côte d'Ivoire", "Hoffenheim", 4.5),
  p("Elye Wahi", "FWD", "Côte d'Ivoire", "Nice", 5.9),

  // Ecuador
  p("Hernán Galíndez", "GK", "Ecuador", "Huracan", 4.2),
  p("Moisés Ramírez", "GK", "Ecuador", "AE Kifisias", 3.9),
  p("Gonzalo Valle", "GK", "Ecuador", "LDU Quito", 3.6),
  p("Willian Pacho", "DEF", "Ecuador", "Paris Saint-Germain", 4.4),
  p("Piero Hincapié", "DEF", "Ecuador", "Arsenal", 4.7),
  p("Joel Ordóñez", "DEF", "Ecuador", "Club Brugge", 3.9),
  p("Félix Torres", "DEF", "Ecuador", "Internacional", 3.9),
  p("Pervis Estupiñán", "DEF", "Ecuador", "AC Milan", 4.8),
  p("Yaimar Medina", "DEF", "Ecuador", "Racing Genk", 3.5),
  p("Ángelo Preciado", "DEF", "Ecuador", "Atlético Mineiro", 4.3),
  p("Jackson Porozo", "DEF", "Ecuador", "Club Tijuana", 3.8),
  p("Alan Minda", "MID", "Ecuador", "Atlético Mineiro", 4.9),
  p("Moisés Caicedo", "MID", "Ecuador", "Chelsea", 6.8),
  p("Jordy Alcivar", "MID", "Ecuador", "Independiente del Valle", 4.9),
  p("Denil Castillo", "MID", "Ecuador", "FC Midtjylland", 4.9),
  p("John Yeboah", "MID", "Ecuador", "Venezia", 5.1),
  p("Alan Franco", "MID", "Ecuador", "Atlético Mineiro", 5.6),
  p("Pedro Vite", "MID", "Ecuador", "Pumas UNAM", 5.2),
  p("Kendry Páez", "MID", "Ecuador", "River Plate", 5.2),
  p("Nilson Angulo", "MID", "Ecuador", "Sunderland", 6),
  p("Gonzalo Plata", "MID", "Ecuador", "Flamengo", 5.6),
  p("Kevin Rodríguez", "FWD", "Ecuador", "Union St.-Gilloise", 4.9),
  p("Anthony Valencia", "FWD", "Ecuador", "Antwerp", 4.2),
  p("Enner Valencia", "FWD", "Ecuador", "Pachuca", 5.9),
  p("Jordy Caicedo", "FWD", "Ecuador", "Huracán", 4.9),
  p("Jeremy Arévalo", "FWD", "Ecuador", "VfB Stuttgart", 4),

  // ── GROUP F ────────────────────────────────────────

  // Netherlands
  p("Mark Flekken", "GK", "Netherlands", "Bayer Leverkusen", 4.7),
  p("Robin Roefs", "GK", "Netherlands", "Sunderland", 4.6),
  p("Bart Verbruggen", "GK", "Netherlands", "Brighton", 4.7),
  p("Nathan Aké", "DEF", "Netherlands", "Manchester City", 5),
  p("Denzel Dumfries", "DEF", "Netherlands", "Inter Milan", 5.7),
  p("Jorrel Hato", "DEF", "Netherlands", "Chelsea", 4.3),
  p("Jurriën Timber", "DEF", "Netherlands", "Arsenal", 5.2),
  p("Jan Paul van Hecke", "DEF", "Netherlands", "Brighton", 4.3),
  p("Micky van de Ven", "DEF", "Netherlands", "Tottenham", 5.1),
  p("Virgil van Dijk", "DEF", "Netherlands", "Liverpool", 5.5),
  p("Frenkie de Jong", "MID", "Netherlands", "Barcelona", 7),
  p("Marten de Roon", "MID", "Netherlands", "Atalanta", 5.1),
  p("Ryan Gravenberch", "MID", "Netherlands", "Liverpool", 6.1),
  p("Teun Koopmeiners", "MID", "Netherlands", "Juventus", 6.2),
  p("Tijjani Reijnders", "MID", "Netherlands", "Manchester City", 6.5),
  p("Guus Til", "MID", "Netherlands", "PSV", 4.9),
  p("Quinten Timber", "MID", "Netherlands", "Marseille", 6.8),
  p("Mats Wieffer", "MID", "Netherlands", "Brighton", 4.8),
  p("Brian Brobbey", "FWD", "Netherlands", "Sunderland", 5.7),
  p("Memphis Depay", "FWD", "Netherlands", "Corinthians", 7.4),
  p("Cody Gakpo", "FWD", "Netherlands", "Liverpool", 7.7),
  p("Justin Kluivert", "FWD", "Netherlands", "Bournemouth", 6.5),
  p("Noa Lang", "FWD", "Netherlands", "Galatasaray", 5.9),
  p("Donyell Malen", "FWD", "Netherlands", "Roma", 6.1),
  p("Crysencio Summerville", "FWD", "Netherlands", "West Ham", 5.3),
  p("Wout Weghorst", "FWD", "Netherlands", "Ajax", 5.5),

  // Japan
  p("Zion Suzuki", "GK", "Japan", "Parma", 4.3),
  p("Keisuke Osako", "GK", "Japan", "Sanfrecce Hiroshima", 4),
  p("Tomoki Hayakawa", "GK", "Japan", "Kashima Antlers", 3.8),
  p("Yūto Nagatomo", "DEF", "Japan", "FC Tokyo", 3.7),
  p("Shogo Taniguchi", "DEF", "Japan", "Sint-Truiden", 3.9),
  p("Ko Itakura", "DEF", "Japan", "Ajax", 4.5),
  p("Tsuyoshi Watanabe", "DEF", "Japan", "Feyenoord", 4.3),
  p("Takehiro Tomiyasu", "DEF", "Japan", "Ajax", 4.9),
  p("Hiroki Ito", "DEF", "Japan", "Bayern Munich", 3.9),
  p("Ayumu Seko", "DEF", "Japan", "Le Havre", 3.8),
  p("Yukinari Sugawara", "DEF", "Japan", "Werder Bremen", 4.4),
  p("Junnosuke Suzuki", "MID", "Japan", "Copenhagen", 3.5),
  p("Wataru Endo", "MID", "Japan", "Liverpool", 6),
  p("Junya Ito", "MID", "Japan", "Genk", 5),
  p("Daichi Kamada", "MID", "Japan", "Crystal Palace", 5.8),
  p("Ritsu Doan", "MID", "Japan", "Eintracht Frankfurt", 5.1),
  p("Ao Tanaka", "MID", "Japan", "Leeds United", 5),
  p("Keito Nakamura", "MID", "Japan", "Reims", 5.5),
  p("Kaishu Sano", "MID", "Japan", "Mainz", 4.9),
  p("Takefusa Kubo", "MID", "Japan", "Real Sociedad", 7),
  p("Yuito Suzuki", "MID", "Japan", "Freiburg", 5),
  p("Koki Ogawa", "FWD", "Japan", "NEC Nijmegen", 4.9),
  p("Daizen Maeda", "FWD", "Japan", "Celtic", 5),
  p("Ayase Ueda", "FWD", "Japan", "Feyenoord", 7),
  p("Kento Shiogai", "FWD", "Japan", "VfL Wolfsburg", 4),
  p("Keisuke Goto", "FWD", "Japan", "Sint-Truiden", 4.2),

  // Sweden
  p("Viktor Johansson", "GK", "Sweden", "Stoke City", 3.9),
  p("Kristoffer Nordfeldt", "GK", "Sweden", "AIK", 3.9),
  p("Jacob Widell Zetterstrom", "GK", "Sweden", "Derby County", 3.7),
  p("Hjalmar Ekdal", "DEF", "Sweden", "Burnley", 3.7),
  p("Gabriel Gudmundsson", "DEF", "Sweden", "Leeds United", 4.2),
  p("Isak Hien", "DEF", "Sweden", "Atalanta", 4.1),
  p("Emil Holm", "DEF", "Sweden", "Juventus", 4.1),
  p("Gustaf Lagerbielke", "DEF", "Sweden", "Braga", 3.7),
  p("Victor Lindelöf", "DEF", "Sweden", "Aston Villa", 4),
  p("Erik Smith", "DEF", "Sweden", "St. Pauli", 4.5),
  p("Carl Starfelt", "DEF", "Sweden", "Celta Vigo", 4.1),
  p("Elliot Stroud", "DEF", "Sweden", "Mjallby", 4.7),
  p("Daniel Svensson", "DEF", "Sweden", "Borussia Dortmund", 4.5),
  p("Taha Ali", "MID", "Sweden", "Malmo", 4.9),
  p("Yasin Ayari", "MID", "Sweden", "Brighton", 5.3),
  p("Lucas Bergvall", "MID", "Sweden", "Tottenham", 5.1),
  p("Jesper Karlström", "MID", "Sweden", "Udinese", 5.6),
  p("Ken Sema", "MID", "Sweden", "Pafos", 6),
  p("Mattias Svanberg", "MID", "Sweden", "Wolfsburg", 6.1),
  p("Besfort Zeneli", "MID", "Sweden", "Union St-Gilloise", 4.7),
  p("Alexander Bernhardsson", "FWD", "Sweden", "Holstein Kiel", 4.9),
  p("Anthony Elanga", "FWD", "Sweden", "Newcastle United", 5.8),
  p("Viktor Gyökeres", "FWD", "Sweden", "Arsenal", 7.8),
  p("Alexander Isak", "FWD", "Sweden", "Liverpool", 8),
  p("Gustaf Nilsson", "FWD", "Sweden", "Club Brugge", 4.9),
  p("Benjamin Nygren", "FWD", "Sweden", "Celtic", 4.9),

  // Tunisia
  p("Aymen Dahmen", "GK", "Tunisia", "CS Sfaxien", 3.9),
  p("Sabri Ben Hessen", "GK", "Tunisia", "Étoile du Sahel", 3.5),
  p("Abdelmouhib Chamakh", "GK", "Tunisia", "Club Africain", 4.1),
  p("Montassar Talbi", "DEF", "Tunisia", "Lorient", 3.9),
  p("Dylan Bronn", "DEF", "Tunisia", "Servette", 3.6),
  p("Omar Rekik", "DEF", "Tunisia", "Maribor", 3.8),
  p("Yan Valery", "DEF", "Tunisia", "Young Boys", 3.9),
  p("Ali Abdi", "DEF", "Tunisia", "Nice", 4.1),
  p("Moutaz Neffati", "DEF", "Tunisia", "IFK Norrköping", 4.1),
  p("Raed Chikhaoui", "DEF", "Tunisia", "US Monastir", 3.5),
  p("Adam Arous", "DEF", "Tunisia", "Kasımpaşa", 4),
  p("Mohamed Amine Ben Hamida", "DEF", "Tunisia", "Espérance de Tunis", 4),
  p("Ellyes Skhiri", "MID", "Tunisia", "Eintracht Frankfurt", 4.7),
  p("Hannibal Mejbri", "MID", "Tunisia", "Burnley", 4.8),
  p("Anis Ben Slimane", "MID", "Tunisia", "Norwich City", 5.3),
  p("Hadj Mahmoud", "MID", "Tunisia", "Lugano", 4.9),
  p("Rani Khedira", "MID", "Tunisia", "Union Berlin", 4.7),
  p("Mortadha Ben Ouanes", "MID", "Tunisia", "Kasımpaşa", 5),
  p("Elias Achouri", "FWD", "Tunisia", "Copenhagen", 4.8),
  p("Ismaël Gharbi", "FWD", "Tunisia", "Augsburg", 4.6),
  p("Elias Saad", "FWD", "Tunisia", "Hannover 96", 4.5),
  p("Sebastian Tounekti", "FWD", "Tunisia", "Celtic", 4.4),
  p("Firas Chaouat", "FWD", "Tunisia", "Club Africain", 4.4),
  p("Khalil Ayari", "FWD", "Tunisia", "Paris Saint-Germain", 4),
  p("Hazem Mastouri", "FWD", "Tunisia", "Dynamo Makhachkala", 4.2),
  p("Rayan Elloumi", "FWD", "Tunisia", "Vancouver Whitecaps", 4),

  // ── GROUP G ────────────────────────────────────────

  // Belgium
  p("Thibaut Courtois", "GK", "Belgium", "Real Madrid", 4.9),
  p("Senne Lammens", "GK", "Belgium", "Manchester United", 4.6),
  p("Mike Penders", "GK", "Belgium", "Chelsea", 3.5),
  p("Timothy Castagne", "DEF", "Belgium", "Fulham", 4.7),
  p("Zeno Debast", "DEF", "Belgium", "Sporting CP", 4.3),
  p("Maxim De Cuyper", "DEF", "Belgium", "Brighton & Hove Albion", 4.7),
  p("Koni De Winter", "DEF", "Belgium", "AC Milan", 4.2),
  p("Brandon Mechele", "DEF", "Belgium", "Club Brugge", 3.9),
  p("Thomas Meunier", "DEF", "Belgium", "Lille", 4.8),
  p("Nathan Ngoy", "DEF", "Belgium", "Lille", 3.7),
  p("Joaquin Seys", "DEF", "Belgium", "Club Brugge", 3.9),
  p("Arthur Theate", "DEF", "Belgium", "Eintracht Frankfurt", 4.5),
  p("Kevin De Bruyne", "MID", "Belgium", "Napoli", 7.5),
  p("Amadou Onana", "MID", "Belgium", "Aston Villa", 5.9),
  p("Nicolas Raskin", "MID", "Belgium", "Rangers", 5.3),
  p("Youri Tielemans", "MID", "Belgium", "Aston Villa", 6.1),
  p("Hans Vanaken", "MID", "Belgium", "Club Brugge", 5.5),
  p("Axel Witsel", "MID", "Belgium", "Girona", 5),
  p("Charles De Ketelaere", "FWD", "Belgium", "Atalanta", 5.6),
  p("Jérémy Doku", "FWD", "Belgium", "Manchester City", 7.5),
  p("Matias Fernandez-Pardo", "FWD", "Belgium", "Lille", 5.6),
  p("Romelu Lukaku", "FWD", "Belgium", "Napoli", 7.4),
  p("Dodi Lukebakio", "FWD", "Belgium", "Benfica", 5.9),
  p("Diego Moreira", "FWD", "Belgium", "Strasbourg", 4.7),
  p("Alexis Saelemaekers", "FWD", "Belgium", "AC Milan", 5.7),
  p("Leandro Trossard", "FWD", "Belgium", "Arsenal", 6.6),

  // Egypt
  p("Mohamed El Shenawy", "GK", "Egypt", "Al Ahly", 3.6),
  p("Mostafa Shobeir", "GK", "Egypt", "Al Ahly", 3.5),
  p("El Mahdy Soliman", "GK", "Egypt", "Zamalek", 3.6),
  p("Mohamed Alaa", "GK", "Egypt", "El Gouna", 3.5),
  p("Mohamed Hany", "DEF", "Egypt", "Al Ahly", 3.6),
  p("Tarek Alaa", "DEF", "Egypt", "Zamalek", 3.5),
  p("Hamdy Fathy", "DEF", "Egypt", "Al Wakrah", 4),
  p("Ramy Rabia", "DEF", "Egypt", "Al Ain", 3.6),
  p("Yasser Ibrahim", "DEF", "Egypt", "Al Ahly", 3.5),
  p("Hossam Abdelmaguid", "DEF", "Egypt", "Zamalek", 3.6),
  p("Mohamed Abdelmonem", "DEF", "Egypt", "Nice", 4),
  p("Ahmed Fatouh", "DEF", "Egypt", "Zamalek", 3.9),
  p("Karim Hafez", "DEF", "Egypt", "Pyramids", 3.9),
  p("Marwan Attia", "MID", "Egypt", "Al Ahly", 4.3),
  p("Mohanad Lasheen", "MID", "Egypt", "Pyramids", 5.3),
  p("Nabil Emad", "MID", "Egypt", "Al Najma", 4.3),
  p("Mahmoud Saber", "MID", "Egypt", "Zed", 4.9),
  p("Ahmed Zizo", "MID", "Egypt", "Al Ahly", 4.3),
  p("Emam Ashour", "MID", "Egypt", "Al Ahly", 4.6),
  p("Mostafa Ziko", "MID", "Egypt", "Pyramids", 4),
  p("Mahmoud Trezeguet", "MID", "Egypt", "Al Ahly", 5.6),
  p("Ibrahim Adel", "MID", "Egypt", "Nordsjaelland", 5.9),
  p("Haissem Hassan", "MID", "Egypt", "Real Oviedo", 4.6),
  p("Omar Marmoush", "FWD", "Egypt", "Manchester City", 7.8),
  p("Mohamed Salah", "FWD", "Egypt", "Liverpool", 10),
  p("Hamza Abdelkarim", "FWD", "Egypt", "Barcelona B", 4.3),

  // Iran
  p("Alireza Beiranvand", "GK", "Iran", "Tractor", 4.2),
  p("Hossein Hosseini", "GK", "Iran", "Sepahan", 3.8),
  p("Payam Niazmand", "GK", "Iran", "Persepolis", 3.9),
  p("Danial Eiri", "DEF", "Iran", "Malavan", 3.5),
  p("Ehsan Hajsafi", "DEF", "Iran", "Sepahan", 4.5),
  p("Saleh Hardani", "DEF", "Iran", "Esteghlal", 3.7),
  p("Hossein Kanaani", "DEF", "Iran", "Persepolis", 4),
  p("Shoka Khalilzadeh", "DEF", "Iran", "Tractor", 4),
  p("Milad Mohammadi", "DEF", "Iran", "Persepolis", 3.8),
  p("Ali Nemati Omid Noorafkan", "DEF", "Iran", "Foolad", 3.5),
  p("Ramin Rezaeian", "DEF", "Iran", "Foolad", 4),
  p("Rouzbeh Cheshmi", "MID", "Iran", "Esteghlal", 4.5),
  p("Saeid Ezatolahi", "MID", "Iran", "Shabab Al-Ahli", 5.6),
  p("Mehdi Ghaedi", "MID", "Iran", "Al-Nasr", 5),
  p("Saman Ghoddos", "MID", "Iran", "Kalba", 4.9),
  p("Mohammad Ghorbani", "MID", "Iran", "Al-Wahda", 5.1),
  p("Alireza Jahanbakhsh", "MID", "Iran", "Dender", 5.3),
  p("Mohammad Mohebi", "MID", "Iran", "Rostovv", 5.9),
  p("Amir Mohammad Razzaghinia", "MID", "Iran", "Esteghlal", 4.2),
  p("Mehdi Torabi", "MID", "Iran", "Tractor", 5.6),
  p("Aria Yousefi", "MID", "Iran", "Sepahan", 3.5),
  p("Ali Alipour", "FWD", "Iran", "Persepolis", 4.6),
  p("Dennis Dargahi", "FWD", "Iran", "Standard Liege", 4.6),
  p("Amirhossein Hosseinzadeh", "FWD", "Iran", "Tractor", 4.5),
  p("Amirhossein Mahmoudi", "FWD", "Iran", "Persepolis", 4),
  p("Mehdi Taremi", "FWD", "Iran", "Olympiacos", 6.1),

  // New Zealand
  p("Max Crocombe", "GK", "New Zealand", "Millwall", 3.9),
  p("Alex Paulsen", "GK", "New Zealand", "Lechia Gdańsk", 3.8),
  p("Michael Woud", "GK", "New Zealand", "Auckland FC", 3.7),
  p("Tim Payne", "DEF", "New Zealand", "Wellington Phoenix", 3.6),
  p("Francis De Vries", "DEF", "New Zealand", "Auckland FC", 3.6),
  p("Tyler Bindon", "DEF", "New Zealand", "Nottingham Forest", 3.6),
  p("Michael Boxall", "DEF", "New Zealand", "Minnesota United", 3.7),
  p("Liberato Cacace", "DEF", "New Zealand", "Wrexham", 4.1),
  p("Nando Pijnaker", "DEF", "New Zealand", "Auckland FC", 3.7),
  p("Finn Surman", "DEF", "New Zealand", "Portland Timbers", 3.5),
  p("Callan Elliot", "DEF", "New Zealand", "Auckland FC", 3.5),
  p("Tommy Smith", "DEF", "New Zealand", "Braintree Town", 3.6),
  p("Joe Bell", "MID", "New Zealand", "Viking FK", 5.1),
  p("Matt Garbett", "MID", "New Zealand", "Peterborough United", 4),
  p("Marko Stamenic", "MID", "New Zealand", "Swansea City", 5.6),
  p("Sarpreet Singh", "MID", "New Zealand", "Wellington Phoenix", 5.3),
  p("Alex Rufer", "MID", "New Zealand", "Wellington Phoenix", 4.9),
  p("Ryan Thomas", "MID", "New Zealand", "PEC Zwolle", 5.3),
  p("Chris Wood", "FWD", "New Zealand", "Nottingham Forest", 6.5),
  p("Eli Just", "FWD", "New Zealand", "Motherwell", 4),
  p("Kosta Barbarouses", "FWD", "New Zealand", "Western Sydney Wanderers", 4.4),
  p("Ben Waine", "FWD", "New Zealand", "Port Vale", 4.2),
  p("Ben Old", "FWD", "New Zealand", "Saint-Étienne", 4.2),
  p("Callum McCowatt", "FWD", "New Zealand", "Silkeborg IF", 4.7),
  p("Jesse Randall", "FWD", "New Zealand", "Auckland FC", 4),
  p("Lachlan Bayliss", "FWD", "New Zealand", "Newcastle Jets", 4),

  // ── GROUP H ────────────────────────────────────────

  // Spain
  p("Unai Simón", "GK", "Spain", "Athletic Club", 5),
  p("David Raya", "GK", "Spain", "Arsenal", 5),
  p("Joan García", "GK", "Spain", "Barcelona", 4),
  p("Marc Cucurella", "DEF", "Spain", "Chelsea", 5.1),
  p("Pau Cubarsí", "DEF", "Spain", "Barcelona", 5),
  p("Aymeric Laporte", "DEF", "Spain", "Athletic Club", 5.5),
  p("Álex Grimaldo", "DEF", "Spain", "Bayer Leverkusen", 7),
  p("Pedro Porro", "DEF", "Spain", "Tottenham Hotspur", 5.5),
  p("Eric García", "DEF", "Spain", "Barcelona", 4.5),
  p("Marcos Llorente", "DEF", "Spain", "Atlético Madrid", 5.5),
  p("Marc Pubill", "DEF", "Spain", "Atlético Madrid", 4.2),
  p("Gavi", "MID", "Spain", "Barcelona", 6.5),
  p("Rodri", "MID", "Spain", "Manchester City", 7.5),
  p("Pedri", "MID", "Spain", "Barcelona", 8.1),
  p("Martín Zubimendi", "MID", "Spain", "Arsenal", 6.1),
  p("Fabián Ruiz", "MID", "Spain", "PSG", 6.8),
  p("Álex Baena", "MID", "Spain", "Atlético Madrid", 6),
  p("Mikel Merino", "MID", "Spain", "Arsenal", 6.2),
  p("Lamine Yamal", "FWD", "Spain", "Barcelona", 10),
  p("Nico Williams", "FWD", "Spain", "Athletic Club", 7.8),
  p("Dani Olmo", "FWD", "Spain", "Barcelona", 7.7),
  p("Ferran Torres", "FWD", "Spain", "Barcelona", 7.8),
  p("Mikel Oyarzabal", "FWD", "Spain", "Real Sociedad", 8.1),
  p("Yéremy Pino", "FWD", "Spain", "Crystal Palace", 5.9),
  p("Borja Iglesias", "FWD", "Spain", "Celta Vigo", 6.8),
  p("Víctor Muñoz", "FWD", "Spain", "Osasuna", 4),

  // Cabo Verde
  p("Vozinha", "GK", "Cabo Verde", "Chaves", 3.9),
  p("Marcio Rosa", "GK", "Cabo Verde", "Montana", 4),
  p("CJ dos Santos", "GK", "Cabo Verde", "San Diego FC", 3.6),
  p("Steven Moreira", "DEF", "Cabo Verde", "Columbus Crew", 3.9),
  p("Wagner Pina", "DEF", "Cabo Verde", "Trabzonspor", 3.8),
  p("Joao Paulo", "DEF", "Cabo Verde", "FCSB", 4.6),
  p("Sidny Lopes Cabral", "DEF", "Cabo Verde", "Benfica", 3.5),
  p("Logan Costa", "DEF", "Cabo Verde", "Villarreal", 3.5),
  p("Pico", "DEF", "Cabo Verde", "Shamrock Rovers", 3.7),
  p("Kelvin Pires", "DEF", "Cabo Verde", "SJK", 3.6),
  p("Stopira", "DEF", "Cabo Verde", "Torreense", 3.5),
  p("Diney", "DEF", "Cabo Verde", "Al Bataeh", 3.5),
  p("Jamiro Monteiro", "MID", "Cabo Verde", "PEC Zwolle", 4.6),
  p("Telmo Arcanjo", "MID", "Cabo Verde", "Vitoria Guimaraes", 4.9),
  p("Yannick Semedo", "MID", "Cabo Verde", "Farense", 4.7),
  p("Laros Duarte", "MID", "Cabo Verde", "Puskas Akademia", 5.1),
  p("Deroy Duarte", "MID", "Cabo Verde", "Ludogorets Razgrad", 4.9),
  p("Kevin Pina", "MID", "Cabo Verde", "Krasnodar", 4.7),
  p("Ryan Mendes", "FWD", "Cabo Verde", "Igdir", 4.9),
  p("Willy Semedo", "FWD", "Cabo Verde", "Omonia", 4.5),
  p("Garry Rodrigues", "FWD", "Cabo Verde", "Apollon Limassol", 4.7),
  p("Jovane Cabral", "FWD", "Cabo Verde", "Estrela Amadora", 4.9),
  p("Nuno da Costa", "FWD", "Cabo Verde", "Istanbul Basaksehir", 4.7),
  p("Dailon Livramento", "FWD", "Cabo Verde", "Casa Pia", 4.9),
  p("Gilson Benchimol", "FWD", "Cabo Verde", "Akron Tolyatti", 5),
  p("Helio Varela", "FWD", "Cabo Verde", "Maccabi Tel Aviv", 4.9),

  // Uruguay
  p("Fernando Muslera", "GK", "Uruguay", "Estudiantes de La Plata", 4.1),
  p("Sergio Rochet", "GK", "Uruguay", "Internacional de Porto Alegre", 4.1),
  p("Santiago Mele", "GK", "Uruguay", "Monterrey", 3.5),
  p("Ronald Araújo", "DEF", "Uruguay", "Barcelona", 5),
  p("José María Giménez", "DEF", "Uruguay", "Atlético Madrid", 4.4),
  p("Santiago Bueno", "DEF", "Uruguay", "Wolverhampton Wanderers", 4.1),
  p("Sebastián Cáceres", "DEF", "Uruguay", "América", 4.2),
  p("Mathías Olivera", "DEF", "Uruguay", "Napoli", 4.3),
  p("Guillermo Varela", "DEF", "Uruguay", "Flamengo", 4.2),
  p("Matías Viña", "DEF", "Uruguay", "River Plate", 4.3),
  p("Joaquín Piquerez", "DEF", "Uruguay", "Palmeiras", 4.5),
  p("Juan Manuel Sanabria", "DEF", "Uruguay", "Real Salt Lake", 4.5),
  p("Federico Valverde", "MID", "Uruguay", "Real Madrid", 7.5),
  p("Rodrigo Bentancur", "MID", "Uruguay", "Tottenham Hotspur", 6),
  p("Manuel Ugarte", "MID", "Uruguay", "Manchester United", 5.9),
  p("Emiliano Martínez", "MID", "Uruguay", "Palmeiras", 4.7),
  p("Rodrigo Zalazar", "MID", "Uruguay", "Sporting CP", 6),
  p("Giorgian De Arrascaeta", "MID", "Uruguay", "Flamengo", 6.5),
  p("Nicolás De La Cruz", "MID", "Uruguay", "Flamengo", 5.9),
  p("Agustín Canobbio", "MID", "Uruguay", "Fluminense", 5.3),
  p("Maximiliano Araújo", "MID", "Uruguay", "Sporting CP", 5.5),
  p("Brian Rodríguez", "MID", "Uruguay", "América", 6.2),
  p("Facundo Pellistri", "MID", "Uruguay", "Panathinaikos", 5.2),
  p("Darwin Núñez", "FWD", "Uruguay", "Al Hilal", 7.5),
  p("Federico Viñas", "FWD", "Uruguay", "Real Oviedo", 5.9),
  p("Rodrigo Aguirre", "FWD", "Uruguay", "Tigres", 5.6),

  // Saudi Arabia
  p("Mohammed Al Owais", "GK", "Saudi Arabia", "Al Ula", 3.5),
  p("Nawaf Al Aqidi", "GK", "Saudi Arabia", "Al Nassr", 4),
  p("Ahmed Al Kassar", "GK", "Saudi Arabia", "Al Qadsiah", 3.9),
  p("Abdulelah Al Amri", "DEF", "Saudi Arabia", "Al Nassr", 3.7),
  p("Hassan Tambakti", "DEF", "Saudi Arabia", "Al Hilal", 4.5),
  p("Jehad Thikri", "DEF", "Saudi Arabia", "Al Qadsiah", 4),
  p("Ali Lajami", "DEF", "Saudi Arabia", "Al Hilal", 3.5),
  p("Hassan Kadesh", "DEF", "Saudi Arabia", "Al Ittihad", 4),
  p("Saud Abdulhamid", "DEF", "Saudi Arabia", "Lens", 4.1),
  p("Mohammed Abu Al Shamat", "DEF", "Saudi Arabia", "Al Qadsiah", 5.5),
  p("Ali Majrashi", "DEF", "Saudi Arabia", "Al Ahli", 3.6),
  p("Moteb Al Harbi", "DEF", "Saudi Arabia", "Al Hilal", 4.1),
  p("Nawaf Boushal", "DEF", "Saudi Arabia", "Al Nassr", 4.5),
  p("Sultan Al-Ghannam", "DEF", "Saudi Arabia", "Al Nassr", 4),
  p("Mohammed Kanno", "MID", "Saudi Arabia", "Al Hilal", 5.5),
  p("Abdullah Al Khaibari", "MID", "Saudi Arabia", "Al Nassr", 5.1),
  p("Ziyad Al Johani", "MID", "Saudi Arabia", "Al Ahli", 4.9),
  p("Nasser Al Dawsari", "MID", "Saudi Arabia", "Al Hilal", 5.2),
  p("Musab Al Juwayr", "MID", "Saudi Arabia", "Al Qadsiah", 4.1),
  p("Alaa Al Hajji", "MID", "Saudi Arabia", "Neom", 4),
  p("Salem Al Dawsari", "MID", "Saudi Arabia", "Al Hilal", 7.2),
  p("Khalid Al Ghannam", "MID", "Saudi Arabia", "Al Ettifaq", 4.9),
  p("Ayman Yahya", "MID", "Saudi Arabia", "Al Nassr", 4),
  p("Firas Al Buraikan", "FWD", "Saudi Arabia", "Al Ahli", 6),
  p("Saleh Al Shehri", "FWD", "Saudi Arabia", "Al Ittihad", 4.9),
  p("Abdullah Al Hamdan", "FWD", "Saudi Arabia", "Al Nassr", 5.5),

  // ── GROUP I ────────────────────────────────────────

  // France
  p("Mike Maignan", "GK", "France", "AC Milan", 5),
  p("Robin Risser", "GK", "France", "Lens", 3.5),
  p("Brice Samba", "GK", "France", "Rennes", 4.5),
  p("Lucas Digne", "DEF", "France", "Aston Villa", 5),
  p("Malo Gusto", "DEF", "France", "Chelsea", 5.1),
  p("Lucas Hernández", "DEF", "France", "Paris Saint-Germain", 5.2),
  p("Theo Hernández", "DEF", "France", "Al Hilal", 5),
  p("Ibrahima Konaté", "DEF", "France", "Liverpool", 4.9),
  p("Jules Koundé", "DEF", "France", "Barcelona", 5.4),
  p("Maxence Lacroix", "DEF", "France", "Crystal Palace", 4.5),
  p("William Saliba", "DEF", "France", "Arsenal", 5.3),
  p("Dayot Upamecano", "DEF", "France", "Bayern Munich", 5.3),
  p("N'Golo Kanté", "MID", "France", "Fenerbahçe", 5.1),
  p("Manu Koné", "MID", "France", "AS Roma", 6.1),
  p("Adrien Rabiot", "MID", "France", "AC Milan", 6.4),
  p("Aurélien Tchouaméni", "MID", "France", "Real Madrid", 6.5),
  p("Warren Zaïre-Emery", "MID", "France", "Paris Saint-Germain", 6.1),
  p("Maghnes Akliouche", "FWD", "France", "AS Monaco", 6.4),
  p("Bradley Barcola", "FWD", "France", "Paris Saint-Germain", 8),
  p("Rayan Cherki", "FWD", "France", "Manchester City", 8),
  p("Ousmane Dembélé", "FWD", "France", "Paris Saint-Germain", 10),
  p("Désiré Doué", "FWD", "France", "Paris Saint-Germain", 7.5),
  p("Jean-Philippe Mateta", "FWD", "France", "Crystal Palace", 6.5),
  p("Kylian Mbappé", "FWD", "France", "Real Madrid", 10.5),
  p("Michael Olise", "FWD", "France", "Bayern Munich", 9.5),
  p("Marcus Thuram", "FWD", "France", "Internazionale", 7.5),

  // Senegal
  p("Édouard Mendy", "GK", "Senegal", "Al Ahli", 4.5),
  p("Mory Diaw", "GK", "Senegal", "Le Havre AC", 3.8),
  p("Yehvann Diouf", "GK", "Senegal", "Nice", 3.9),
  p("Krépin Diatta", "DEF", "Senegal", "AS Monaco", 6.1),
  p("Antoine Mendy", "DEF", "Senegal", "Nice", 3.7),
  p("Kalidou Koulibaly", "DEF", "Senegal", "Al Hilal", 4.9),
  p("El Hadji Malick Diouf", "DEF", "Senegal", "West Ham United", 4.1),
  p("Mamadou Sarr", "DEF", "Senegal", "Chelsea", 4.7),
  p("Moussa Niakhaté", "DEF", "Senegal", "Lyon", 4.3),
  p("Abdoulaye Seck", "DEF", "Senegal", "Maccabi Haifa", 3.8),
  p("Ismail Jakobs", "DEF", "Senegal", "Galatasaray", 4.1),
  p("Idrissa Gana Gueye", "MID", "Senegal", "Everton", 6),
  p("Pape Gueye", "MID", "Senegal", "Villarreal", 5.9),
  p("Lamine Camara", "MID", "Senegal", "AS Monaco", 6.2),
  p("Habib Diarra", "MID", "Senegal", "Sunderland", 6.2),
  p("Pathé Ciss", "MID", "Senegal", "Rayo Vallecano", 5.6),
  p("Pape Matar Sarr", "MID", "Senegal", "Tottenham Hotspur", 5.6),
  p("Bara Sapoko Ndiaye", "MID", "Senegal", "Bayern Munich", 4.5),
  p("Sadio Mané", "FWD", "Senegal", "Al Nassr", 7.6),
  p("Ismaïla Sarr", "FWD", "Senegal", "Crystal Palace", 6.2),
  p("Iliman Ndiaye", "FWD", "Senegal", "Everton", 6.5),
  p("Assane Diao", "FWD", "Senegal", "Como", 4.9),
  p("Ibrahim Mbaye", "FWD", "Senegal", "Paris Saint-Germain", 4.4),
  p("Nicolas Jackson", "FWD", "Senegal", "Chelsea", 6.7),
  p("Bamba Dieng", "FWD", "Senegal", "Lorient", 4.9),
  p("Cherif Ndiaye", "FWD", "Senegal", "Samsunspor", 4.9),

  // Iraq
  p("Fahad Talib", "GK", "Iraq", "Al-Talaba", 3.7),
  p("Jalal Hassan", "GK", "Iraq", "Al-Zawraa", 3.9),
  p("Ahmed Basil", "GK", "Iraq", "Al-Shorta", 3.8),
  p("Hussein Ali", "DEF", "Iraq", "Pogoń Szczecin", 3.6),
  p("Manaf Younis", "DEF", "Iraq", "Al-Shorta", 4),
  p("Zaid Tahseen", "DEF", "Iraq", "Pakhtakor", 3.6),
  p("Rebin Sulaka", "DEF", "Iraq", "Port FC", 3.7),
  p("Akam Hashem", "DEF", "Iraq", "Al-Zawraa", 4),
  p("Merchas Doski", "DEF", "Iraq", "Viktoria Plzeň", 3.8),
  p("Ahmed Yahya", "DEF", "Iraq", "Al-Shorta", 3.6),
  p("Zaid Ismail", "DEF", "Iraq", "Al-Talaba", 4),
  p("Frans Putros", "DEF", "Iraq", "Port FC", 3.7),
  p("Mustafa Saadoon", "DEF", "Iraq", "Al-Shorta", 3.6),
  p("Amir Al-Ammari", "MID", "Iraq", "Cracovia", 5.3),
  p("Kevin Yakob", "MID", "Iraq", "AGF Aarhus", 5.1),
  p("Zidane Iqbal", "MID", "Iraq", "FC Utrecht", 5.6),
  p("Aimar Sher", "MID", "Iraq", "Sarpsborg 08", 5.3),
  p("Ibrahim Bayesh", "MID", "Iraq", "Al-Riyadh", 5.6),
  p("Ahmed Qasim", "MID", "Iraq", "Elfsborg", 4),
  p("Youssef Amyn", "MID", "Iraq", "Eintracht Braunschweig", 4.4),
  p("Marko Farji", "MID", "Iraq", "Strømsgodset", 4.4),
  p("Ali Jasim", "FWD", "Iraq", "Como", 4.9),
  p("Ali Al-Hamadi", "FWD", "Iraq", "Ipswich Town", 4.7),
  p("Ali Yousef", "FWD", "Iraq", "Al-Shorta", 4),
  p("Aymen Hussein", "FWD", "Iraq", "Al-Khor", 5.3),
  p("Mohanad Ali", "FWD", "Iraq", "Al-Shorta", 4.9),

  // Norway
  p("Ørjan Nyland", "GK", "Norway", "Sevilla", 4.2),
  p("Egil Selvik", "GK", "Norway", "Watford", 3.8),
  p("Sander Tangvik", "GK", "Norway", "Hamburg SV", 3.5),
  p("Julian Ryerson", "DEF", "Norway", "Borussia Dortmund", 4.2),
  p("Kristoffer Ajer", "DEF", "Norway", "Brentford", 4.3),
  p("Leo Østigård", "DEF", "Norway", "Genoa", 4.1),
  p("David Møller Wolfe", "DEF", "Norway", "Wolverhampton Wanderers", 4),
  p("Marcus Pedersen", "DEF", "Norway", "Torino", 4.1),
  p("Torbjørn Heggem", "DEF", "Norway", "Bologna", 3.7),
  p("Fredrik André Bjørkan", "DEF", "Norway", "Bodø/Glimt", 4.5),
  p("Henrik Falchener", "DEF", "Norway", "Viking", 3.5),
  p("Sondre Langås", "DEF", "Norway", "Derby County", 4),
  p("Martin Ødegaard", "MID", "Norway", "Arsenal", 7.7),
  p("Sander Berge", "MID", "Norway", "Fulham", 4.7),
  p("Patrick Berg", "MID", "Norway", "Bodø/Glimt", 5.6),
  p("Kristian Thorstvedt", "MID", "Norway", "Sassuolo", 6.2),
  p("Morten Thorsby", "MID", "Norway", "Cremonese", 5.6),
  p("Thelo Aasgaard", "MID", "Norway", "Rangers", 5.5),
  p("Andreas Schjelderup", "MID", "Norway", "Benfica", 6.2),
  p("Jens Petter Hauge", "MID", "Norway", "Bodø/Glimt", 5.9),
  p("Fredrik Aursnes", "MID", "Norway", "Benfica", 6.5),
  p("Oscar Bobb", "MID", "Norway", "Fulham", 5.1),
  p("Antonio Nusa", "MID", "Norway", "RB Leipzig", 6.1),
  p("Erling Haaland", "FWD", "Norway", "Manchester City", 10.5),
  p("Alexander Sørloth", "FWD", "Norway", "Atlético Madrid", 6.8),
  p("Jørgen Strand Larsen", "FWD", "Norway", "Crystal Palace", 5.6),

  // ── GROUP J ────────────────────────────────────────

  // Argentina
  p("Emiliano Martínez", "GK", "Argentina", "Aston Villa", 4.7),
  p("Gerónimo Rulli", "GK", "Argentina", "Marseille", 4.5),
  p("Juan Musso", "GK", "Argentina", "Atlético Madrid", 4.3),
  p("Gonzalo Montiel", "DEF", "Argentina", "River Plate", 4.3),
  p("Nahuel Molina", "DEF", "Argentina", "Atlético Madrid", 4.4),
  p("Lisandro Martínez", "DEF", "Argentina", "Manchester United", 4.6),
  p("Nicolás Otamendi", "DEF", "Argentina", "Benfica", 4.4),
  p("Leonardo Balerdi", "DEF", "Argentina", "Marseille", 4),
  p("Cristian Romero", "DEF", "Argentina", "Tottenham", 4.9),
  p("Facundo Medina", "DEF", "Argentina", "Marseille", 4),
  p("Nicolás Tagliafico", "DEF", "Argentina", "Lyon", 4.3),
  p("Leandro Paredes", "MID", "Argentina", "Boca Juniors", 5.6),
  p("Rodrigo De Paul", "MID", "Argentina", "Inter Miami", 5.9),
  p("Exequiel Palacios", "MID", "Argentina", "Bayer Leverkusen", 6),
  p("Enzo Fernández", "MID", "Argentina", "Chelsea", 7.5),
  p("Alexis Mac Allister", "MID", "Argentina", "Liverpool", 6.6),
  p("Giovani Lo Celso", "MID", "Argentina", "Real Betis", 6.2),
  p("Valentín Barco", "MID", "Argentina", "Strasbourg", 6.2),
  p("Lionel Messi", "FWD", "Argentina", "Inter Miami", 10),
  p("Nico Paz", "FWD", "Argentina", "Como", 5.9),
  p("Thiago Almada", "FWD", "Argentina", "Atlético Madrid", 6.5),
  p("Nicolás González", "FWD", "Argentina", "Atletico Madrid", 6),
  p("Giuliano Simeone", "FWD", "Argentina", "Atlético Madrid", 5.6),
  p("Lautaro Martínez", "FWD", "Argentina", "Internazionale", 8.8),
  p("Jose Manuel López", "FWD", "Argentina", "Palmeiras", 5.3),
  p("Julián Álvarez", "FWD", "Argentina", "Atlético Madrid", 8.6),

  // Algeria
  p("Oussama Benbot", "GK", "Algeria", "USM Alger", 4.2),
  p("Melvin Masstil", "GK", "Algeria", "Stade Nyonnaise", 4),
  p("Luca Zidane", "GK", "Algeria", "Granada", 3.8),
  p("Achraf Abada", "DEF", "Algeria", "USM Alger", 4),
  p("Rayan Ait Nouri", "DEF", "Algeria", "Manchester City", 4.9),
  p("Zinedine Belaid", "DEF", "Algeria", "JS Kabylie", 4),
  p("Rafik Belghali", "DEF", "Algeria", "Verona", 3.5),
  p("Ramy Bensebaini", "DEF", "Algeria", "Borussia Dortmund", 4.4),
  p("Samir Chergui", "DEF", "Algeria", "Paris FC", 4),
  p("Jaouen Hadjam", "DEF", "Algeria", "Young Boys", 3.8),
  p("Aissa Mandi", "DEF", "Algeria", "Lille", 3.9),
  p("Mohamed Amine Tougai", "DEF", "Algeria", "Esperance", 4),
  p("Houssem Aouar", "MID", "Algeria", "Al Ittihad", 6),
  p("Nabil Bentaleb", "MID", "Algeria", "Lille", 5.5),
  p("Hicham Boudaoui", "MID", "Algeria", "Nice", 5.5),
  p("Fares Chaibi", "MID", "Algeria", "Eintracht Frankfurt", 6.2),
  p("Ibrahim Maza", "MID", "Algeria", "Bayer Leverkusen", 5.4),
  p("Yassine Titraoui", "MID", "Algeria", "Charleroi", 4.5),
  p("Ramiz Zerrouki", "MID", "Algeria", "FC Twente", 5.3),
  p("Mohamed Amine Amoura", "FWD", "Algeria", "VfL Wolfsburg", 6.5),
  p("Nadir Benbouali", "FWD", "Algeria", "Győri ETO", 4),
  p("Adil Boulbina", "FWD", "Algeria", "Al Duhail", 4),
  p("Fares Ghedjemis", "FWD", "Algeria", "Frosinone", 4.4),
  p("Amine Gouiri", "FWD", "Algeria", "Marseille", 6.2),
  p("Riyad Mahrez", "FWD", "Algeria", "Al Ahli", 6.5),
  p("Anis Hadj Moussa", "FWD", "Algeria", "Feyenoord", 5.3),

  // Austria
  p("Alexander Schlager", "GK", "Austria", "RB Salzburg", 4.6),
  p("Florian Wiegele", "GK", "Austria", "Viktoria Plzen", 3.5),
  p("Patrick Pentz", "GK", "Austria", "Brondby", 4.6),
  p("David Affengruber", "DEF", "Austria", "Elche", 3.9),
  p("Kevin Danso", "DEF", "Austria", "Tottenham", 4.3),
  p("Stefan Posch", "DEF", "Austria", "Mainz 05", 4.3),
  p("David Alaba", "DEF", "Austria", "Real Madrid", 4.6),
  p("Philipp Lienhart", "DEF", "Austria", "SC Freiburg", 4.3),
  p("Philipp Mwene", "DEF", "Austria", "Mainz 05", 4.5),
  p("Alexander Prass", "DEF", "Austria", "TSG Hoffenheim", 4.3),
  p("Marco Friedl", "DEF", "Austria", "Werder Bremen", 4.3),
  p("Michael Svoboda", "DEF", "Austria", "Venezia", 3.8),
  p("Xaver Schlager", "MID", "Austria", "RB Leipzig", 5.5),
  p("Nicolas Seiwald", "MID", "Austria", "RB Leipzig", 5.6),
  p("Marcel Sabitzer", "MID", "Austria", "Borussia Dortmund", 6.8),
  p("Florian Grillitsch", "MID", "Austria", "Braga", 5.5),
  p("Carney Chukwuemeka", "MID", "Austria", "Borussia Dortmund", 5),
  p("Romano Schmid", "MID", "Austria", "Werder Bremen", 6),
  p("Christoph Baumgartner", "MID", "Austria", "RB Leipzig", 6.7),
  p("Konrad Laimer", "MID", "Austria", "Bayern Munich", 5.8),
  p("Patrick Wimmer", "MID", "Austria", "Wolfsburg", 6),
  p("Paul Wanner", "MID", "Austria", "PSV Eindhoven", 5.6),
  p("Alessandro Schopf", "MID", "Austria", "Wolfsberger AC", 5.3),
  p("Marko Arnautovic", "FWD", "Austria", "Red Star Belgrade", 6),
  p("Michael Gregoritsch", "FWD", "Austria", "FC Augsburg", 6),
  p("Sasa Kalajdzic", "FWD", "Austria", "LASK Linz", 6),

  // Jordan
  p("Yazid Abulaila", "GK", "Jordan", "Al-Hussein", 4),
  p("Abdallah Al-Fakhouri", "GK", "Jordan", "Al-Wehdat", 3.6),
  p("Nour Bani Attiah", "GK", "Jordan", "Al-Faisaly", 4),
  p("Ihsan Haddad", "DEF", "Jordan", "Al-Hussein", 4),
  p("Saed Al-Rosan", "DEF", "Jordan", "Al-Hussein", 3.5),
  p("Mohammad Abualnadi", "DEF", "Jordan", "Selangor", 3.5),
  p("Husam Abu Dahab", "DEF", "Jordan", "Al-Faisaly", 4),
  p("Mohammed Abu Hashish", "DEF", "Jordan", "Al-Karma", 4),
  p("Yazan Al-Arab", "DEF", "Jordan", "FC Seoul", 3.7),
  p("Anas Badawi", "DEF", "Jordan", "Al-Faisaly", 3.5),
  p("Abdallah Nasib", "DEF", "Jordan", "Al-Zawraa", 3.6),
  p("Saleem Obaid", "DEF", "Jordan", "Al-Hussein", 3.5),
  p("Mohammed Al-Dawoud", "MID", "Jordan", "Al-Wehdat", 4),
  p("Nizar Al-Rashdan", "MID", "Jordan", "Qatar SC", 4.9),
  p("Noor Al-Rawabdeh", "MID", "Jordan", "Selangor", 4.7),
  p("Rajaei Ayed", "MID", "Jordan", "Al-Hussein", 4.5),
  p("Amer Jamous", "MID", "Jordan", "Al-Zawraa", 3.5),
  p("Ibrahim Sadeh", "MID", "Jordan", "Al-Karma", 4.4),
  p("Mohannad Abu Taha", "MID", "Jordan", "Al-Quwa Al-Jawiya", 3.5),
  p("Mohammed Abu Zrayq", "FWD", "Jordan", "Raja Casablanca", 4.5),
  p("Mousa Al-Tamari", "FWD", "Jordan", "Rennes", 5.6),
  p("Ali Azaizeh", "FWD", "Jordan", "Al-Shabab", 4),
  p("Odeh Al-Fakhouri", "FWD", "Jordan", "Pyramids", 4),
  p("Ali Olwan", "FWD", "Jordan", "Al-Sailiaya", 4.2),
  p("Ibrahim Sabra", "FWD", "Jordan", "Lokomotiva Zagreb", 4),
  p("Mahmoud Al-Mardi", "FWD", "Jordan", "Al-Hussein", 4.2),

  // ── GROUP K ────────────────────────────────────────

  // Portugal
  p("Diogo Costa", "GK", "Portugal", "Porto", 4.9),
  p("José Sá", "GK", "Portugal", "Wolverhampton Wanderers", 4.7),
  p("Rui Silva", "GK", "Portugal", "Sporting Lisbon", 4.7),
  p("Ricardo Velho", "GK", "Portugal", "Gençlerbirliği", 4),
  p("Rúben Dias", "DEF", "Portugal", "Manchester City", 5),
  p("João Cancelo", "DEF", "Portugal", "Barcelona", 5.3),
  p("Diogo Dalot", "DEF", "Portugal", "Manchester United", 5),
  p("Nuno Mendes", "DEF", "Portugal", "Paris Saint-Germain", 5.8),
  p("Nélson Semedo", "DEF", "Portugal", "Fenerbahce", 4.3),
  p("Matheus Nunes", "DEF", "Portugal", "Manchester City", 6.1),
  p("Gonçalo Inacio", "DEF", "Portugal", "Sporting Lisbon", 4.6),
  p("Renato Veiga", "DEF", "Portugal", "Villarreal", 4.3),
  p("Tomás Araújo", "DEF", "Portugal", "Benfica", 4.1),
  p("Bruno Fernandes", "MID", "Portugal", "Manchester United", 8.5),
  p("Bernardo Silva", "MID", "Portugal", "Manchester City", 7.8),
  p("Vitinha", "MID", "Portugal", "PSG", 6.4),
  p("João Neves", "MID", "Portugal", "PSG", 6.5),
  p("Rúben Neves", "MID", "Portugal", "Al Hilal", 5.9),
  p("Samú Costa", "MID", "Portugal", "Mallorca", 5.6),
  p("Cristiano Ronaldo", "FWD", "Portugal", "Al Nassr", 10),
  p("Rafael Leão", "FWD", "Portugal", "AC Milan", 7.8),
  p("João Félix", "FWD", "Portugal", "Al Nassr", 6.5),
  p("Gonçalo Ramos", "FWD", "Portugal", "PSG", 7.5),
  p("Pedro Neto", "FWD", "Portugal", "Chelsea", 6.4),
  p("Francisco Conceição", "FWD", "Portugal", "Juventus", 5.7),
  p("Gonçalo Guedes", "FWD", "Portugal", "Real Sociedad", 5.8),
  p("Francisco Trincão", "FWD", "Portugal", "Sporting Lisbon", 5.9),

  // Congo DR
  p("Lionel Mpasi", "GK", "Congo DR", "Le Havre", 4),
  p("Timothy Fayulu", "GK", "Congo DR", "FC Noah", 3.6),
  p("Matthieu Epolo", "GK", "Congo DR", "Standard Liege", 3.7),
  p("Chancel Mbemba", "DEF", "Congo DR", "Lille", 4.2),
  p("Axel Tuanzebe", "DEF", "Congo DR", "Burnley", 4),
  p("Arthur Masuaku", "DEF", "Congo DR", "Lens", 4.2),
  p("Gedeon Kalulu", "DEF", "Congo DR", "Aris Limassol", 3.9),
  p("Joris Kayembe", "DEF", "Congo DR", "Genk", 3.9),
  p("Aaron Wan-Bissaka", "DEF", "Congo DR", "West Ham United", 4.3),
  p("Aaron Tshibola", "DEF", "Congo DR", "Kilmarnock", 4.9),
  p("Steve Kapuadi", "DEF", "Congo DR", "Widzew Łódź", 3.7),
  p("Dylan Batubinsika", "DEF", "Congo DR", "AEL", 3.8),
  p("Noah Sadiki", "MID", "Congo DR", "Sunderland", 5.3),
  p("Charles Pickel", "MID", "Congo DR", "Espanyol", 5.3),
  p("Edo Kayembe", "MID", "Congo DR", "Watford", 5.6),
  p("Samuel Moutoussamy", "MID", "Congo DR", "Atromitos", 5.1),
  p("Ngal'ayel Mukau", "MID", "Congo DR", "Lille", 4.9),
  p("Nathanaël Mbuku", "MID", "Congo DR", "Montpellier", 4.5),
  p("Meschak Elia", "MID", "Congo DR", "Alanyaspor", 5.5),
  p("Brian Cipenga", "MID", "Congo DR", "Castellón", 4.2),
  p("Gaël Kakuta", "MID", "Congo DR", "AEL", 4.6),
  p("Théo Bongonda", "MID", "Congo DR", "Spartak Moscow", 6.2),
  p("Simon Banza", "FWD", "Congo DR", "Al Jazira", 5.6),
  p("Yoane Wissa", "FWD", "Congo DR", "Newcastle United", 6.2),
  p("Fiston Mayele", "FWD", "Congo DR", "Pyramids FC", 4.9),
  p("Cédric Bakambu", "FWD", "Congo DR", "Real Betis", 6.5),

  // Uzbekistan
  p("Utkir Yusupov", "GK", "Uzbekistan", "Navbahor", 3.9),
  p("Botirali Ergashev", "GK", "Uzbekistan", "AGMK", 3.5),
  p("Abduvokhid Nematov", "GK", "Uzbekistan", "Nasaf", 4),
  p("Avazbek Ulmasaliev", "DEF", "Uzbekistan", "AGMK", 4),
  p("Jakhongir Urozov", "DEF", "Uzbekistan", "Dinamo Samarqand", 3.5),
  p("Rustamjon Ashurmatov", "DEF", "Uzbekistan", "Esteghlal", 4),
  p("Umarbek Eshmurodov", "DEF", "Uzbekistan", "Nasaf", 4),
  p("Abdukodir Khusanov", "DEF", "Uzbekistan", "Manchester City", 4.3),
  p("Abdulla Abdullaev", "DEF", "Uzbekistan", "Dibba Al Fujairah", 4.2),
  p("Farrukh Sayfiev", "DEF", "Uzbekistan", "Neftchi", 3.6),
  p("Khojiakbar Alijonov", "DEF", "Uzbekistan", "Pakhtakor", 3.6),
  p("Sherzod Nasrullaev", "DEF", "Uzbekistan", "Nasaf", 3.7),
  p("Behruz Karimov", "DEF", "Uzbekistan", "Surkhon", 4),
  p("Sherzod Esanov", "MID", "Uzbekistan", "Buxoro", 4.7),
  p("Umarali Rakhmonaliev", "MID", "Uzbekistan", "Sabah", 5.1),
  p("Akmal Mozgovoy", "MID", "Uzbekistan", "Pakhtakor", 4.7),
  p("Otabek Shukurov", "MID", "Uzbekistan", "Baniyas", 5),
  p("Jamshid Iskanderov", "MID", "Uzbekistan", "Neftchi", 5.7),
  p("Azizjon Ganiev", "MID", "Uzbekistan", "Al Bataeh", 4),
  p("Abbosek Fayzullaev", "MID", "Uzbekistan", "Istanbul Basaksehir", 5.5),
  p("Jaloliddin Masharipov", "MID", "Uzbekistan", "Esteghlal", 6.1),
  p("Dostonbek Khamdamov", "MID", "Uzbekistan", "Pakhtakor", 5.1),
  p("Oston Urunov", "MID", "Uzbekistan", "Persepolis", 5.6),
  p("Azizbek Amonov", "FWD", "Uzbekistan", "Buxoro", 4),
  p("Igor Sergeev", "FWD", "Uzbekistan", "Persepolis", 6.1),
  p("Eldor Shomurodov", "FWD", "Uzbekistan", "Istanbul Basaksehir", 6.5),

  // Colombia
  p("David Ospina", "GK", "Colombia", "Atlético Nacional", 4),
  p("Álvaro Montero", "GK", "Colombia", "Vélez Sarsfield", 3.8),
  p("Camilo Vargas", "GK", "Colombia", "Atlas", 4.3),
  p("Daniel Muñoz", "DEF", "Colombia", "Crystal Palace", 4.6),
  p("Jhon Lucumí", "DEF", "Colombia", "Bologna", 4.3),
  p("Santiago Arias", "DEF", "Colombia", "Independiente", 3.9),
  p("Davinson Sánchez", "DEF", "Colombia", "Galatasaray", 4.3),
  p("Johan Mojica", "DEF", "Colombia", "Mallorca", 3.9),
  p("Yerry Mina", "DEF", "Colombia", "Cagliari", 4.2),
  p("Willer Ditta", "DEF", "Colombia", "Cruz Azul", 3.7),
  p("Deiver Machado", "DEF", "Colombia", "Nantes", 3.9),
  p("Jorge Carrascal", "MID", "Colombia", "Flamengo", 6.1),
  p("Kevin Castaño", "MID", "Colombia", "River Plate", 4.3),
  p("Gustavo Puerta", "MID", "Colombia", "Racing Santander", 5.3),
  p("Juan Fernando Quintero", "MID", "Colombia", "River Plate", 5.6),
  p("Juan Portilla", "MID", "Colombia", "Athletico Paranaense", 4.7),
  p("Jefferson Lerma", "MID", "Colombia", "Crystal Palace", 4.9),
  p("Richard Ríos", "MID", "Colombia", "Benfica", 4.7),
  p("Jhon Arias", "MID", "Colombia", "Palmeiras", 6.3),
  p("James Rodríguez", "MID", "Colombia", "Minnesota United", 6.5),
  p("Jaminton Campaz", "MID", "Colombia", "Rosario Central", 5.5),
  p("Luis Díaz", "FWD", "Colombia", "Bayern Munich", 8.1),
  p("Jhon Córdoba", "FWD", "Colombia", "Krasnodar", 6.1),
  p("Luis Suárez", "FWD", "Colombia", "Sporting CP", 5.7),
  p("Andrés Gómez", "FWD", "Colombia", "Vasco da Gama", 4.9),
  p("Cucho Hernández", "FWD", "Colombia", "Real Betis", 6.3),

  // ── GROUP L ────────────────────────────────────────

  // England
  p("Jordan Pickford", "GK", "England", "Everton", 4.8),
  p("Dean Henderson", "GK", "England", "Crystal Palace", 4.2),
  p("James Trafford", "GK", "England", "Manchester City", 4),
  p("Reece James", "DEF", "England", "Chelsea", 5.2),
  p("Ezri Konsa", "DEF", "England", "Aston Villa", 4.8),
  p("Jarell Quansah", "DEF", "England", "Bayer Leverkusen", 4.4),
  p("John Stones", "DEF", "England", "Manchester City", 4.6),
  p("Marc Guéhi", "DEF", "England", "Manchester City", 5.1),
  p("Dan Burn", "DEF", "England", "Newcastle United", 4.5),
  p("Nico O'Reilly", "DEF", "England", "Manchester City", 4.7),
  p("Djed Spence", "DEF", "England", "Tottenham Hotspur", 4.5),
  p("Tino Livramento", "DEF", "England", "Newcastle United", 4.6),
  p("Declan Rice", "MID", "England", "Arsenal", 7),
  p("Elliot Anderson", "MID", "England", "Nottingham Forest", 6.5),
  p("Kobbie Mainoo", "MID", "England", "Manchester United", 6.1),
  p("Jordan Henderson", "MID", "England", "Brentford", 5.1),
  p("Morgan Rogers", "MID", "England", "Aston Villa", 7.2),
  p("Jude Bellingham", "MID", "England", "Real Madrid", 8.3),
  p("Eberechi Eze", "MID", "England", "Arsenal", 8),
  p("Harry Kane", "FWD", "England", "Bayern Munich", 10.5),
  p("Ivan Toney", "FWD", "England", "Al-Ahli", 7.5),
  p("Ollie Watkins", "FWD", "England", "Aston Villa", 7.9),
  p("Bukayo Saka", "FWD", "England", "Arsenal", 9.5),
  p("Marcus Rashford", "FWD", "England", "Manchester United", 7.5),
  p("Anthony Gordon", "FWD", "England", "Newcastle United", 7),
  p("Noni Madueke", "FWD", "England", "Arsenal", 6.1),

  // Croatia
  p("Dominik Livakovic", "GK", "Croatia", "Dinamo Zagreb", 4.5),
  p("Dominik Kotarski", "GK", "Croatia", "Kobenhavn", 4.4),
  p("Ivor Pandur", "GK", "Croatia", "Hull City", 3.9),
  p("Josko Gvardiol", "DEF", "Croatia", "Manchester City", 5),
  p("Duje Caleta-Car", "DEF", "Croatia", "Real Sociedad", 4),
  p("Josip Sutalo", "DEF", "Croatia", "Ajax", 4.3),
  p("Josip Stanisic", "DEF", "Croatia", "Bayern Munich", 4.3),
  p("Marin Pongracic", "DEF", "Croatia", "Fiorentina", 4),
  p("Martin Erlic", "DEF", "Croatia", "Midtjylland", 3.9),
  p("Luka Vuskovic", "DEF", "Croatia", "Hamburg", 3.7),
  p("Luka Modric", "MID", "Croatia", "AC Milan", 6.2),
  p("Mateo Kovacic", "MID", "Croatia", "Manchester City", 6),
  p("Mario Pasalic", "MID", "Croatia", "Atalanta", 6.4),
  p("Nikola Vlasic", "MID", "Croatia", "Torino", 6.1),
  p("Luka Sucic", "MID", "Croatia", "Real Sociedad", 4.9),
  p("Martin Baturina", "MID", "Croatia", "Como", 6.5),
  p("Kristijan Jakic", "MID", "Croatia", "Augsburg", 5.6),
  p("Petar Sucic", "MID", "Croatia", "Inter Milan", 4.2),
  p("Nikola Moro", "MID", "Croatia", "Bologna", 5.6),
  p("Toni Fruk", "MID", "Croatia", "Rijeka", 4.9),
  p("Ivan Perisic", "FWD", "Croatia", "PSV Eindhoven", 5.4),
  p("Andrej Kramaric", "FWD", "Croatia", "Hoffenheim", 6.2),
  p("Ante Budimir", "FWD", "Croatia", "Osasuna", 6.8),
  p("Marco Pasalic", "FWD", "Croatia", "Orlando City", 5.3),
  p("Petar Musa", "FWD", "Croatia", "FC Dallas", 5.1),
  p("Igor Matanovic", "FWD", "Croatia", "Freiburg", 4.9),

  // Ghana
  p("Benjamin Asare", "GK", "Ghana", "Accra Hearts of Oak SC", 3.8),
  p("Lawrence Ati-Zigi", "GK", "Ghana", "St Gallen", 4),
  p("Joseph Anang", "GK", "Ghana", "St Patrick's Athletic", 3.6),
  p("Baba Abdul Rahman", "DEF", "Ghana", "PAOK Salonika", 4.5),
  p("Gideon Mensah", "DEF", "Ghana", "AJ Auxerre", 3.9),
  p("Marvin Senaya", "DEF", "Ghana", "AJ Auxerre", 3.5),
  p("Alidu Seidu", "DEF", "Ghana", "Stade Rennais", 3.9),
  p("Abdul Mumin", "DEF", "Ghana", "Rayo Vallecano", 3.7),
  p("Jerome Opoku", "DEF", "Ghana", "Istanbul Basaksehir", 3.8),
  p("Jonas Adjetey", "DEF", "Ghana", "VfL Wolfsburg", 3.5),
  p("Kojo Oppong Peprah", "DEF", "Ghana", "Nice", 4.5),
  p("Derrick Luckassen", "DEF", "Ghana", "Pafos", 3.7),
  p("Elisha Owusu", "MID", "Ghana", "AJ Auxerre", 5.3),
  p("Thomas Partey", "MID", "Ghana", "Villarreal", 6.2),
  p("Kwasi Sibo", "MID", "Ghana", "Real Oviedo", 4.7),
  p("Augustine Boakye", "MID", "Ghana", "Saint-Étienne", 4.9),
  p("Caleb Yirenkyi", "MID", "Ghana", "FC Nordsjælland", 4.7),
  p("Abdul Fatawu Issahaku", "MID", "Ghana", "Leicester City", 6.4),
  p("Kamal Deen Sulemana", "FWD", "Ghana", "Atalanta", 5.1),
  p("Christopher Bonsu Baah", "FWD", "Ghana", "Al Qadsiah", 4.5),
  p("Ernest Nuamah", "FWD", "Ghana", "Lyon", 5),
  p("Antoine Semenyo", "FWD", "Ghana", "Manchester City", 7.2),
  p("Brandon Thomas-Asante", "FWD", "Ghana", "Coventry City", 5.1),
  p("Prince Kwabena Adu", "FWD", "Ghana", "Viktoria Plzen", 4),
  p("Iñaki Williams", "FWD", "Ghana", "Athletic Club", 5.9),
  p("Jordan Ayew", "FWD", "Ghana", "Leicester City", 5.3),

  // Panama
  p("Orlando Mosquera", "GK", "Panama", "Al Fayha", 3.9),
  p("Luis Mejía", "GK", "Panama", "Nacional", 4),
  p("César Samudio", "GK", "Panama", "Marathón", 3.6),
  p("César Blackman", "DEF", "Panama", "Slovan Bratislava", 3.7),
  p("Jorge Gutiérrez", "DEF", "Panama", "Deportivo La Guaira", 3.5),
  p("Amir Murillo", "DEF", "Panama", "Beşiktaş", 5),
  p("Fidel Escobar", "DEF", "Panama", "Saprissa", 3.8),
  p("Andrés Andrade", "DEF", "Panama", "LASK", 3.7),
  p("Edgardo Fariña", "DEF", "Panama", "Pari Nizhny Novgorod", 3.9),
  p("José Córdoba", "DEF", "Panama", "Norwich City", 4),
  p("Éric Davis", "DEF", "Panama", "Plaza Amador", 3.9),
  p("Jiovany Ramos", "DEF", "Panama", "Puerto Cabello", 3.5),
  p("Roderick Miller", "DEF", "Panama", "Turan Tovuz", 3.5),
  p("Aníbal Godoy", "MID", "Panama", "San Diego FC", 5.6),
  p("Adalberto Carrasquilla", "MID", "Panama", "Pumas UNAM", 6.5),
  p("Carlos Harvey", "MID", "Panama", "Minnesota United", 4.9),
  p("Cristian Martínez", "MID", "Panama", "Ironi Kiryat Shmona", 5.3),
  p("José Luis Rodríguez", "MID", "Panama", "Juárez", 5.6),
  p("César Yanis", "MID", "Panama", "Cobresal", 4.4),
  p("Yoel Bárcenas", "MID", "Panama", "Mazatlán", 5.6),
  p("Alberto Quintero", "MID", "Panama", "Plaza Amador", 4.2),
  p("Azarias Londoño", "MID", "Panama", "Universidad Católica", 4.4),
  p("Ismael Díaz", "FWD", "Panama", "León", 4.9),
  p("Cecilio Waterman", "FWD", "Panama", "Universidad de Concepción", 5),
  p("José Fajardo", "FWD", "Panama", "Universidad Católica", 4.7),
  p("Tomás Rodríguez", "FWD", "Panama", "Saprissa", 4.5),
];
